//! Core Wasm host-binding generator.
//!
//! Parses a WIT package and generates Rust source that hosts a Core Wasm
//! module using the WIT canonical ABI: typed host imports registered on a
//! `wasmtime::Linker`, plus typed guest-export callers. The generated module
//! assumes the guest was built with `wit-bindgen` 0.60 targeting
//! `wasm32-wasip1`, whose exports return an indirect result pointer and expose
//! `cabi_post_*` release functions.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use wit_parser::abi::{AbiVariant, WasmType};
use wit_parser::{
    Function, FunctionKind, Interface, Resolve, SizeAlign, Type, TypeDefKind, TypeId, WorldId,
    WorldItem,
};

mod host_import;

#[derive(Clone, Copy)]
enum ExportCallVariant {
    Store,
    Caller,
}

pub struct Bindgen {
    resolve: Resolve,
    world: WorldId,
    sizes: SizeAlign,
    out: String,
    tmp: usize,
}

impl Bindgen {
    pub fn new(resolve: Resolve, world: WorldId) -> Self {
        let mut sizes = SizeAlign::default();
        sizes.fill(&resolve);
        Self {
            resolve,
            world,
            sizes,
            out: String::new(),
            tmp: 0,
        }
    }

    pub fn generate(&mut self) -> String {
        self.out.clear();
        let _ = writeln!(
            self.out,
            "// Generated by aegilex-core-bindgen from wit/world.wit. Do not edit."
        );
        let _ = writeln!(self.out, "#[allow(warnings)]");
        let _ = writeln!(self.out, "pub mod core_host {{");
        self.emit_helpers();
        self.emit_types();
        self.emit_imports();
        self.emit_exports();
        let _ = writeln!(self.out, "}}");
        std::mem::take(&mut self.out)
    }

    /// Generates default-denied implementations of every imported-interface
    /// host trait for an arbitrary store type. Lets a production store type
    /// satisfy the full generated trait set before per-interface semantics are
    /// ported; concrete `impl`s in the runtime then override these.
    pub fn generate_store_impls(&mut self, store_type: &str, exclude: &[&str]) -> String {
        self.out.clear();
        let _ = writeln!(
            self.out,
            "// Generated by aegilex-core-bindgen. Default-denied host trait impls for {store_type}."
        );
        let _ = writeln!(self.out, "use crate::core_host::*;");
        let _ = writeln!(self.out, "use crate::core_host::imports::*;");
        let _ = writeln!(self.out, "use crate::runtime::PluginStoreState;");
        let interfaces: Vec<Interface> = self.resolve.worlds[self.world]
            .imports
            .iter()
            .filter_map(|(_, item)| match item {
                wit_parser::WorldItem::Interface { id, .. } => {
                    Some(self.resolve.interfaces[*id].clone())
                }
                _ => None,
            })
            .collect();
        for interface in &interfaces {
            let iface_name = interface.name.clone().expect("interface name");
            if exclude.contains(&iface_name.as_str()) {
                continue;
            }
            let trait_name = format!("Host{}", Self::rust_ident(&iface_name));
            let _ = writeln!(self.out, "impl {trait_name} for {store_type} {{");
            for function in interface.functions.values() {
                self.emit_denied_method(interface, function);
            }
            for (resource_name, resource_id) in &interface.types {
                if !matches!(self.resolve.types[*resource_id].kind, TypeDefKind::Resource) {
                    continue;
                }
                let drop_method = format!("drop_{}", resource_name.replace('-', "_"));
                let _ = writeln!(
                    self.out,
                    "    fn {drop_method}(&mut self, _handle: u32) -> Result<(), String> {{ Ok(()) }}"
                );
            }
            let _ = writeln!(self.out, "}}");
        }
        std::mem::take(&mut self.out)
    }

    /// Emits one default-denied method body for `function` of `interface`.
    fn emit_denied_method(&mut self, interface: &Interface, function: &Function) {
        let mut method_params = Vec::new();
        let mut param_names = Vec::new();
        for param in &function.params {
            method_params.push(format!(
                "{}: {}",
                Self::sanitize_field(&param.name),
                self.rust_type(&param.ty)
            ));
            param_names.push(Self::sanitize_field(&param.name));
        }
        let params = method_params.join(", ");
        let result_ty = match &function.result {
            Some(ty) => self.rust_type(ty),
            None => "()".to_owned(),
        };
        let method_name = match &function.kind {
            FunctionKind::Method(resource) => {
                let resource_name = self.resolve.types[*resource]
                    .name
                    .as_deref()
                    .expect("resource name")
                    .replace('-', "_");
                format!(
                    "{}_{}",
                    resource_name,
                    function.item_name().replace('-', "_")
                )
            }
            _ => function.item_name().replace('-', "_"),
        };
        let _ = writeln!(
            self.out,
            "    fn {method_name}(&mut self, {params}) -> Result<{result_ty}, String> {{"
        );
        if !param_names.is_empty() {
            let _ = writeln!(self.out, "        let _ = {};", param_names.join(", "));
        }
        let denied = match &function.result {
            Some(Type::Id(result_id)) => match &self.resolve.types[*result_id].kind {
                TypeDefKind::Result(result) => match &result.err {
                    Some(Type::Id(err_id)) => {
                        let mut current = *err_id;
                        let is_enum = loop {
                            match &self.resolve.types[current].kind {
                                TypeDefKind::Enum(_) => break true,
                                TypeDefKind::Type(Type::Id(next)) => current = *next,
                                _ => break false,
                            }
                        };
                        if is_enum {
                            let err_ty = self.rust_type(&Type::Id(current));
                            format!("Ok(Err({err_ty}::Denied))")
                        } else {
                            "Ok(Err(\"denied by default policy\".to_owned()))".to_owned()
                        }
                    }
                    _ => "Ok(Err(\"denied by default policy\".to_owned()))".to_owned(),
                },
                _ => "Err(\"denied by default policy\".to_owned())".to_owned(),
            },
            _ => "Err(\"denied by default policy\".to_owned())".to_owned(),
        };
        let _ = writeln!(self.out, "        {denied}");
        let _ = writeln!(self.out, "    }}");
        let _ = interface;
    }

    fn world_types(&self) -> Vec<TypeId> {
        // Reachable types = all interface types of imported/exported
        // interfaces, in deterministic interface order.
        let mut ids = Vec::new();
        for (_, item) in self.resolve.worlds[self.world]
            .imports
            .iter()
            .chain(self.resolve.worlds[self.world].exports.iter())
        {
            if let WorldItem::Interface { id, .. } = item {
                for type_id in self.resolve.interfaces[*id].types.values() {
                    ids.push(*type_id);
                }
            }
        }
        ids
    }

    fn interface_of(&self, id: TypeId) -> Option<Interface> {
        // Interfaces are identified by type membership; lookup through the
        // world's interface items.
        let mut found = None;
        for (_, item) in self.resolve.worlds[self.world]
            .imports
            .iter()
            .chain(self.resolve.worlds[self.world].exports.iter())
        {
            if let WorldItem::Interface { id: iface_id, .. } = item {
                let iface = &self.resolve.interfaces[*iface_id];
                if iface.types.values().any(|ty| *ty == id) {
                    found = Some(*iface_id);
                    break;
                }
            }
        }
        found.map(|iface_id| self.resolve.interfaces[iface_id].clone())
    }

    fn rust_ident(kebab: &str) -> String {
        kebab
            .split(['-', '_'])
            .map(|part| {
                let mut chars = part.chars();
                match chars.next() {
                    Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                    None => String::new(),
                }
            })
            .collect()
    }

    fn type_rust_name(&self, id: TypeId) -> String {
        let name = self.resolve.types[id].name.clone().expect("named type");
        let iface = self.interface_of(id).expect("type belongs to an interface");
        let iface_name = iface.name.expect("interface has a name");
        format!(
            "{}{}",
            Self::rust_ident(&iface_name),
            Self::rust_ident(&name)
        )
    }

    fn scalar_type(&self, ty: &Type) -> Option<&'static str> {
        match ty {
            Type::Bool => Some("bool"),
            Type::U8 => Some("u8"),
            Type::U16 => Some("u16"),
            Type::U32 => Some("u32"),
            Type::U64 => Some("u64"),
            Type::S8 => Some("i8"),
            Type::S16 => Some("i16"),
            Type::S32 => Some("i32"),
            Type::S64 => Some("i64"),
            Type::F32 => Some("f32"),
            Type::F64 => Some("f64"),
            Type::Char => Some("char"),
            _ => None,
        }
    }

    fn rust_type(&self, ty: &Type) -> String {
        match ty {
            Type::Bool
            | Type::U8
            | Type::U16
            | Type::U32
            | Type::U64
            | Type::S8
            | Type::S16
            | Type::S32
            | Type::S64
            | Type::F32
            | Type::F64
            | Type::Char => self.scalar_type(ty).unwrap().to_owned(),
            Type::ErrorContext => "u32".to_owned(),
            Type::String => "String".to_owned(),
            Type::Id(id) => match &self.resolve.types[*id].kind {
                TypeDefKind::Type(inner) => self.rust_type(inner),
                TypeDefKind::List(inner) => format!("Vec<{}>", self.rust_type(inner)),
                TypeDefKind::Option(inner) => format!("Option<{}>", self.rust_type(inner)),
                TypeDefKind::Result(result) => {
                    let ok = result
                        .ok
                        .as_ref()
                        .map(|ty| self.rust_type(ty))
                        .unwrap_or_else(|| "()".to_owned());
                    let err = result
                        .err
                        .as_ref()
                        .map(|ty| self.rust_type(ty))
                        .unwrap_or_else(|| "()".to_owned());
                    format!("Result<{ok}, {err}>")
                }
                TypeDefKind::Tuple(tuple) => {
                    let fields = tuple
                        .types
                        .iter()
                        .map(|ty| self.rust_type(ty))
                        .collect::<Vec<_>>()
                        .join(", ");
                    format!("({fields})")
                }
                TypeDefKind::Handle(_) => "u32".to_owned(),
                _ => self.type_rust_name(*id),
            },
        }
    }

    fn emit_helpers(&mut self) {
        let _ = writeln!(
            self.out,
            r#"
use anyhow::anyhow;
use wasmtime::{{AsContext, AsContextMut, Caller, Instance, Linker, Memory, Store}};
use wasmtime_wasi::preview1::WasiP1Ctx;

pub(crate) fn trap(message: impl std::fmt::Display) -> anyhow::Error {{
    anyhow!("{{message}}")
}}

fn mem_of<T>(caller: &mut Caller<'_, T>) -> anyhow::Result<Memory> {{
    caller
        .get_export("memory")
        .and_then(|export| export.into_memory())
        .ok_or_else(|| trap("missing memory export"))
}}

fn alloc<T>(caller: &mut Caller<'_, T>, mem: &Memory, size: usize, align: usize) -> anyhow::Result<i32> {{
    let size = i32::try_from(size).map_err(|_| trap("allocation size out of range"))?;
    let align = i32::try_from(align).map_err(|_| trap("allocation alignment out of range"))?;
    let realloc = caller
        .get_export("cabi_realloc")
        .and_then(|export| export.into_func())
        .ok_or_else(|| trap("missing cabi_realloc"))?;
    let realloc = realloc
        .typed::<(i32, i32, i32, i32), i32>(&*caller)
        .map_err(|error| trap(format!("cabi_realloc typing failed: {{error}}")))?;
    realloc
        .call(&mut *caller, (0, 0, align, size))
        .map_err(|error| trap(format!("cabi_realloc failed: {{error}}")))
}}

fn lift_string<T>(caller: &mut Caller<'_, T>, mem: &Memory, ptr: i32, len: i32) -> anyhow::Result<String> {{
    let ptr = usize::try_from(ptr).map_err(|_| trap("string pointer out of range"))?;
    let len = usize::try_from(len).map_err(|_| trap("string length out of range"))?;
    let bytes = mem
        .data(caller.as_context())
        .get(ptr..)
        .and_then(|slice| slice.get(..len))
        .ok_or_else(|| trap("string out of bounds"))?;
    std::str::from_utf8(bytes)
        .map(str::to_owned)
        .map_err(|error| trap(format!("invalid UTF-8: {{error}}")))
}}

fn lift_string_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize) -> anyhow::Result<String> {{
    let ptr = read_i32_at(caller, mem, base, offset)?;
    let len = read_i32_at(caller, mem, base, offset + 4)?;
    lift_string(caller, mem, ptr, len)
}}

fn lower_string_into<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize, value: &str) -> anyhow::Result<()> {{
    let size = value.len();
    let ptr = alloc(caller, mem, size, 1)?;
    let ptr_usize = usize::try_from(ptr).map_err(|_| trap("allocation pointer out of range"))?;
    mem.data_mut(caller.as_context_mut())
        .get_mut(ptr_usize..)
        .and_then(|slice| slice.get_mut(..size))
        .ok_or_else(|| trap("allocation out of bounds"))?
        .copy_from_slice(value.as_bytes());
    let base = usize::try_from(base).map_err(|_| trap("result area out of range"))?;
    let slot = mem
        .data_mut(caller.as_context_mut())
        .get_mut(base + offset..)
        .and_then(|slice| slice.get_mut(..8))
        .ok_or_else(|| trap("result area out of bounds"))?;
    let size = i32::try_from(size).map_err(|_| trap("string too large"))?;
    slot[..4].copy_from_slice(&ptr.to_le_bytes());
    slot[4..].copy_from_slice(&size.to_le_bytes());
    Ok(())
}}

fn read_bytes<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize, len: usize) -> anyhow::Result<Vec<u8>> {{
    let base = usize::try_from(base).map_err(|_| trap("pointer out of range"))?;
    Ok(mem
        .data(caller.as_context())
        .get(base + offset..)
        .and_then(|slice| slice.get(..len))
        .ok_or_else(|| trap("read out of bounds"))?
        .to_vec())
}}

fn read_i32_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize) -> anyhow::Result<i32> {{
    let base = usize::try_from(base).map_err(|_| trap("pointer out of range"))?;
    let bytes = mem
        .data(caller.as_context())
        .get(base + offset..)
        .and_then(|slice| slice.get(..4))
        .ok_or_else(|| trap("read out of bounds"))?;
    Ok(i32::from_le_bytes(bytes.try_into().expect("4 bytes")))
}}

fn read_i64_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize) -> anyhow::Result<i64> {{
    let base = usize::try_from(base).map_err(|_| trap("pointer out of range"))?;
    let bytes = mem
        .data(caller.as_context())
        .get(base + offset..)
        .and_then(|slice| slice.get(..8))
        .ok_or_else(|| trap("read out of bounds"))?;
    Ok(i64::from_le_bytes(bytes.try_into().expect("8 bytes")))
}}

fn read_f32_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize) -> anyhow::Result<f32> {{
    Ok(f32::from_bits(read_i32_at(caller, mem, base, offset)? as u32))
}}

fn read_f64_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize) -> anyhow::Result<f64> {{
    Ok(f64::from_bits(read_i64_at(caller, mem, base, offset)? as u64))
}}

fn read_i32_at_s<T: AsContext>(store: &T, mem: &Memory, base: i32, offset: usize) -> anyhow::Result<i32> {{
    let base = usize::try_from(base).map_err(|_| trap("pointer out of range"))?;
    let bytes = mem
        .data(store.as_context())
        .get(base + offset..)
        .and_then(|slice| slice.get(..4))
        .ok_or_else(|| trap("read out of bounds"))?;
    Ok(i32::from_le_bytes(bytes.try_into().expect("4 bytes")))
}}

fn read_i64_at_s<T: AsContext>(store: &T, mem: &Memory, base: i32, offset: usize) -> anyhow::Result<i64> {{
    let base = usize::try_from(base).map_err(|_| trap("pointer out of range"))?;
    let bytes = mem
        .data(store.as_context())
        .get(base + offset..)
        .and_then(|slice| slice.get(..8))
        .ok_or_else(|| trap("read out of bounds"))?;
    Ok(i64::from_le_bytes(bytes.try_into().expect("8 bytes")))
}}

fn read_f32_at_s<T: AsContext>(store: &T, mem: &Memory, base: i32, offset: usize) -> anyhow::Result<f32> {{
    Ok(f32::from_bits(read_i32_at_s(store, mem, base, offset)? as u32))
}}

fn read_f64_at_s<T: AsContext>(store: &T, mem: &Memory, base: i32, offset: usize) -> anyhow::Result<f64> {{
    Ok(f64::from_bits(read_i64_at_s(store, mem, base, offset)? as u64))
}}

fn lift_string_at_s<T: AsContext>(store: &T, mem: &Memory, base: i32, offset: usize) -> anyhow::Result<String> {{
    let ptr = read_i32_at_s(store, mem, base, offset)?;
    let len = read_i32_at_s(store, mem, base, offset + 4)?;
    let ptr = usize::try_from(ptr).map_err(|_| trap("string pointer out of range"))?;
    let len = usize::try_from(len).map_err(|_| trap("string length out of range"))?;
    let bytes = mem
        .data(store.as_context())
        .get(ptr..)
        .and_then(|slice| slice.get(..len))
        .ok_or_else(|| trap("string out of bounds"))?;
    std::str::from_utf8(bytes)
        .map(str::to_owned)
        .map_err(|error| trap(format!("invalid UTF-8: {{error}}")))
}}

fn lift_list_string_at_s<T: AsContext>(store: &T, mem: &Memory, base: i32, offset: usize) -> anyhow::Result<Vec<String>> {{
    let ptr = read_i32_at_s(store, mem, base, offset)?;
    let len = read_i32_at_s(store, mem, base, offset + 4)?;
    let len = usize::try_from(len).map_err(|_| trap("list length out of range"))?;
    let mut values = Vec::with_capacity(len);
    for index in 0..len {{
        let element_offset = index.checked_mul(8).ok_or_else(|| trap("list offset overflow"))?;
        values.push(lift_string_at_s(store, mem, ptr, element_offset)?);
    }}
    Ok(values)
}}

fn alloc_s<T: AsContextMut>(store: &mut T, instance: &Instance, mem: &Memory, size: usize, align: usize) -> anyhow::Result<i32> {{
    let size = i32::try_from(size).map_err(|_| trap("allocation size out of range"))?;
    let align = i32::try_from(align).map_err(|_| trap("allocation alignment out of range"))?;
    let realloc = instance
        .get_export(&mut *store, "cabi_realloc")
        .and_then(|export| export.into_func())
        .ok_or_else(|| trap("missing cabi_realloc"))?;
    let realloc = realloc
        .typed::<(i32, i32, i32, i32), i32>(&*store)
        .map_err(|error| trap(format!("cabi_realloc typing failed: {{error}}")))?;
    realloc
        .call(&mut *store, (0, 0, align, size))
        .map_err(|error| trap(format!("cabi_realloc failed: {{error}}")))
}}

fn write_i32_at_s<T: AsContextMut>(store: &mut T, mem: &Memory, base: i32, offset: usize, value: i32) -> anyhow::Result<()> {{
    let base = usize::try_from(base).map_err(|_| trap("pointer out of range"))?;
    mem.data_mut(store.as_context_mut())
        .get_mut(base + offset..)
        .and_then(|slice| slice.get_mut(..4))
        .ok_or_else(|| trap("write out of bounds"))?
        .copy_from_slice(&value.to_le_bytes());
    Ok(())
}}

fn write_i64_at_s<T: AsContextMut>(store: &mut T, mem: &Memory, base: i32, offset: usize, value: i64) -> anyhow::Result<()> {{
    let base = usize::try_from(base).map_err(|_| trap("pointer out of range"))?;
    mem.data_mut(store.as_context_mut())
        .get_mut(base + offset..)
        .and_then(|slice| slice.get_mut(..8))
        .ok_or_else(|| trap("write out of bounds"))?
        .copy_from_slice(&value.to_le_bytes());
    Ok(())
}}

fn write_f32_at_s<T: AsContextMut>(store: &mut T, mem: &Memory, base: i32, offset: usize, value: f32) -> anyhow::Result<()> {{
    write_i32_at_s(store, mem, base, offset, value.to_bits() as i32)
}}

fn write_f64_at_s<T: AsContextMut>(store: &mut T, mem: &Memory, base: i32, offset: usize, value: f64) -> anyhow::Result<()> {{
    write_i64_at_s(store, mem, base, offset, value.to_bits() as i64)
}}

fn write_string_at_s<T: AsContextMut>(store: &mut T, instance: &Instance, mem: &Memory, base: i32, offset: usize, value: &str) -> anyhow::Result<()> {{
    let size = value.len();
    let ptr = alloc_s(store, instance, mem, size, 1)?;
    let ptr_usize = usize::try_from(ptr).map_err(|_| trap("allocation pointer out of range"))?;
    mem.data_mut(store.as_context_mut())
        .get_mut(ptr_usize..)
        .and_then(|slice| slice.get_mut(..size))
        .ok_or_else(|| trap("allocation out of bounds"))?
        .copy_from_slice(value.as_bytes());
    let base = usize::try_from(base).map_err(|_| trap("result area out of range"))?;
    let slot = mem
        .data_mut(store.as_context_mut())
        .get_mut(base + offset..)
        .and_then(|slice| slice.get_mut(..8))
        .ok_or_else(|| trap("result area out of bounds"))?;
    let size = i32::try_from(size).map_err(|_| trap("string too large"))?;
    slot[..4].copy_from_slice(&ptr.to_le_bytes());
    slot[4..].copy_from_slice(&size.to_le_bytes());
    Ok(())
}}

fn write_list_string_at_s<T: AsContextMut>(store: &mut T, instance: &Instance, mem: &Memory, base: i32, offset: usize, values: &[String]) -> anyhow::Result<()> {{
    let total = values.len().checked_mul(8).ok_or_else(|| trap("list size overflow"))?;
    let elems = alloc_s(store, instance, mem, total, 4)?;
    let elems = usize::try_from(elems).map_err(|_| trap("list pointer out of range"))?;
    for (index, value) in values.iter().enumerate() {{
        let element = elems.checked_add(index * 8).ok_or_else(|| trap("list offset overflow"))?;
        let ptr = alloc_s(store, instance, mem, value.len(), 1)?;
        let ptr_usize = usize::try_from(ptr).map_err(|_| trap("string pointer out of range"))?;
        mem.data_mut(store.as_context_mut())
            .get_mut(ptr_usize..)
            .and_then(|slice| slice.get_mut(..value.len()))
            .ok_or_else(|| trap("string out of bounds"))?
            .copy_from_slice(value.as_bytes());
        let slot = mem
            .data_mut(store.as_context_mut())
            .get_mut(element..)
            .and_then(|slice| slice.get_mut(..8))
            .ok_or_else(|| trap("list element out of bounds"))?;
        let size = i32::try_from(value.len()).map_err(|_| trap("string too large"))?;
        slot[..4].copy_from_slice(&ptr.to_le_bytes());
        slot[4..].copy_from_slice(&size.to_le_bytes());
    }}
    let elems = i32::try_from(elems).map_err(|_| trap("list pointer out of range"))?;
    let len = i32::try_from(values.len()).map_err(|_| trap("list length out of range"))?;
    write_i32_at_s(store, mem, base, offset, elems)?;
    write_i32_at_s(store, mem, base, offset + 4, len)?;
    Ok(())
}}

fn lower_list_string_param_s<T: AsContextMut>(store: &mut T, instance: &Instance, mem: &Memory, values: &[String]) -> anyhow::Result<i32> {{
    let total = values.len().checked_mul(8).ok_or_else(|| trap("list size overflow"))?;
    let elems = alloc_s(store, instance, mem, total, 4)?;
    let elems = usize::try_from(elems).map_err(|_| trap("list pointer out of range"))?;
    for (index, value) in values.iter().enumerate() {{
        let element = elems.checked_add(index * 8).ok_or_else(|| trap("list offset overflow"))?;
        let ptr = alloc_s(store, instance, mem, value.len(), 1)?;
        let ptr_usize = usize::try_from(ptr).map_err(|_| trap("string pointer out of range"))?;
        mem.data_mut(store.as_context_mut())
            .get_mut(ptr_usize..)
            .and_then(|slice| slice.get_mut(..value.len()))
            .ok_or_else(|| trap("string out of bounds"))?
            .copy_from_slice(value.as_bytes());
        let slot = mem
            .data_mut(store.as_context_mut())
            .get_mut(element..)
            .and_then(|slice| slice.get_mut(..8))
            .ok_or_else(|| trap("list element out of bounds"))?;
        let size = i32::try_from(value.len()).map_err(|_| trap("string too large"))?;
        slot[..4].copy_from_slice(&ptr.to_le_bytes());
        slot[4..].copy_from_slice(&size.to_le_bytes());
    }}
    i32::try_from(elems).map_err(|_| trap("list pointer out of range"))
}}

fn write_u8_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize, value: i32) -> anyhow::Result<()> {{
    let base = usize::try_from(base).map_err(|_| trap("pointer out of range"))?;
    let slot = mem.data_mut(caller.as_context_mut())
        .get_mut(base + offset)
        .ok_or_else(|| trap("write out of bounds"))?;
    *slot = value as u8;
    Ok(())
}}

fn write_u16_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize, value: i32) -> anyhow::Result<()> {{
    let base = usize::try_from(base).map_err(|_| trap("pointer out of range"))?;
    mem.data_mut(caller.as_context_mut())
        .get_mut(base + offset..)
        .and_then(|slice| slice.get_mut(..2))
        .ok_or_else(|| trap("write out of bounds"))?
        .copy_from_slice(&(value as u16).to_le_bytes());
    Ok(())
}}

fn write_i32_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize, value: i32) -> anyhow::Result<()> {{
    let base = usize::try_from(base).map_err(|_| trap("pointer out of range"))?;
    mem.data_mut(caller.as_context_mut())
        .get_mut(base + offset..)
        .and_then(|slice| slice.get_mut(..4))
        .ok_or_else(|| trap("write out of bounds"))?
        .copy_from_slice(&value.to_le_bytes());
    Ok(())
}}

fn write_i64_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize, value: i64) -> anyhow::Result<()> {{
    let base = usize::try_from(base).map_err(|_| trap("pointer out of range"))?;
    mem.data_mut(caller.as_context_mut())
        .get_mut(base + offset..)
        .and_then(|slice| slice.get_mut(..8))
        .ok_or_else(|| trap("write out of bounds"))?
        .copy_from_slice(&value.to_le_bytes());
    Ok(())
}}

fn write_f32_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize, value: f32) -> anyhow::Result<()> {{
    write_i32_at(caller, mem, base, offset, value.to_bits() as i32)
}}

fn write_f64_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize, value: f64) -> anyhow::Result<()> {{
    write_i64_at(caller, mem, base, offset, value.to_bits() as i64)
}}

fn lower_list_string_into<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize, values: &[String]) -> anyhow::Result<()> {{
    let elem_size = 8usize;
    let total = values.len().checked_mul(elem_size).ok_or_else(|| trap("list size overflow"))?;
    let elems = alloc(caller, mem, total, 4)?;
    let elems = usize::try_from(elems).map_err(|_| trap("list pointer out of range"))?;
    for (index, value) in values.iter().enumerate() {{
        let element = elems.checked_add(index * elem_size).ok_or_else(|| trap("list offset overflow"))?;
        let ptr = alloc(caller, mem, value.len(), 1)?;
        let ptr = usize::try_from(ptr).map_err(|_| trap("string pointer out of range"))?;
        mem.data_mut(caller.as_context_mut())
            .get_mut(ptr..)
            .and_then(|slice| slice.get_mut(..value.len()))
            .ok_or_else(|| trap("string out of bounds"))?
            .copy_from_slice(value.as_bytes());
        let size = i32::try_from(value.len()).map_err(|_| trap("string too large"))?;
        let ptr = i32::try_from(ptr).map_err(|_| trap("string pointer out of range"))?;
        let slot = mem
            .data_mut(caller.as_context_mut())
            .get_mut(element..)
            .and_then(|slice| slice.get_mut(..8))
            .ok_or_else(|| trap("list element out of bounds"))?;
        slot[..4].copy_from_slice(&ptr.to_le_bytes());
        slot[4..].copy_from_slice(&size.to_le_bytes());
    }}
    let elems = i32::try_from(elems).map_err(|_| trap("list pointer out of range"))?;
    let len = i32::try_from(values.len()).map_err(|_| trap("list length out of range"))?;
    write_i32_at(caller, mem, base, offset, elems)?;
    write_i32_at(caller, mem, base, offset + 4, len)?;
    Ok(())
}}

fn lift_list_string_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize) -> anyhow::Result<Vec<String>> {{
    let ptr = read_i32_at(caller, mem, base, offset)?;
    let len = read_i32_at(caller, mem, base, offset + 4)?;
    let len = usize::try_from(len).map_err(|_| trap("list length out of range"))?;
    let mut values = Vec::with_capacity(len);
    for index in 0..len {{
        let element_offset = index.checked_mul(8).ok_or_else(|| trap("list offset overflow"))?;
        values.push(lift_string_at(caller, mem, ptr, element_offset)?);
    }}
    Ok(values)
}}
"#,
        );
    }

    fn sanitize_field(name: &str) -> String {
        let snake = name.replace('-', "_");
        match snake.as_str() {
            "type" | "match" | "ref" | "move" | "box" | "as" | "if" | "else" | "in" | "for"
            | "loop" | "while" | "where" | "impl" | "trait" | "fn" | "let" | "static" | "const"
            | "pub" | "use" | "mod" | "struct" | "enum" | "unsafe" | "async" | "await" | "dyn"
            | "super" | "crate" | "return" | "break" | "continue" => {
                format!("r#{snake}")
            }
            "self" => "self_".to_owned(),
            _ => snake,
        }
    }

    fn emit_types(&mut self) {
        let mut emitted = BTreeSet::new();
        for id in self.world_types() {
            if !emitted.insert(id) {
                continue;
            }
            let name = self.type_rust_name(id);
            match &self.resolve.types[id].kind {
                TypeDefKind::Record(record) => {
                    let fields = record
                        .fields
                        .iter()
                        .map(|field| {
                            format!(
                                "pub {}: {},",
                                Self::sanitize_field(&field.name),
                                self.rust_type(&field.ty)
                            )
                        })
                        .collect::<Vec<_>>()
                        .join("\n    ");
                    let _ = writeln!(self.out, "    #[derive(Debug, Clone, PartialEq)]");
                    let _ = writeln!(self.out, "    pub struct {name} {{");
                    let _ = writeln!(self.out, "    {fields}");
                    let _ = writeln!(self.out, "    }}");
                }
                TypeDefKind::Enum(enum_) => {
                    let _ = writeln!(self.out, "    #[derive(Debug, Clone, Copy, PartialEq, Eq)]");
                    let _ = writeln!(self.out, "    #[repr(i32)]");
                    let _ = writeln!(self.out, "    pub enum {name} {{");
                    for (index, case) in enum_.cases.iter().enumerate() {
                        let _ = writeln!(
                            self.out,
                            "        {} = {index},",
                            Self::rust_ident(&case.name)
                        );
                    }
                    let _ = writeln!(self.out, "    }}");
                }
                TypeDefKind::Variant(variant) => {
                    let _ = writeln!(self.out, "    #[derive(Debug, Clone, PartialEq)]");
                    let _ = writeln!(self.out, "    pub enum {name} {{");
                    for case in &variant.cases {
                        let case_name = Self::rust_ident(&case.name);
                        match &case.ty {
                            Some(ty) => {
                                let _ = writeln!(
                                    self.out,
                                    "        {case_name}({}),",
                                    self.rust_type(ty)
                                );
                            }
                            None => {
                                let _ = writeln!(self.out, "        {case_name},");
                            }
                        }
                    }
                    let _ = writeln!(self.out, "    }}");
                }
                TypeDefKind::Flags(flags) => {
                    let fields = flags
                        .flags
                        .iter()
                        .map(|flag| format!("pub {}: bool,", Self::sanitize_field(&flag.name)))
                        .collect::<Vec<_>>()
                        .join("\n    ");
                    let _ = writeln!(self.out, "    #[derive(Debug, Clone, Copy, PartialEq, Eq)]");
                    let _ = writeln!(self.out, "    pub struct {name} {{");
                    let _ = writeln!(self.out, "    {fields}");
                    let _ = writeln!(self.out, "    }}");
                }
                TypeDefKind::Resource => {
                    // Export-side resource: guest-owned, host passes its rep.
                    let _ = writeln!(self.out, "    #[derive(Debug, Clone, Copy, PartialEq, Eq)]");
                    let _ = writeln!(self.out, "    pub struct {name}(pub u32);");
                }
                _ => {}
            }
        }
    }

    fn emit_imports(&mut self) {
        // Collect imported interfaces in deterministic order.
        let mut imports: Vec<(String, Interface)> = Vec::new();
        for (name, item) in self.resolve.worlds[self.world].imports.iter() {
            if let WorldItem::Interface { id, .. } = item {
                imports.push((name.clone().into(), self.resolve.interfaces[*id].clone()));
            }
        }
        if imports.is_empty() {
            return;
        }
        let _ = writeln!(self.out, "    pub mod imports {{");
        let _ = writeln!(self.out, "        use super::*;");
        for (_, interface) in &imports {
            let iface_name = interface.name.clone().expect("interface name");
            let trait_name = format!("Host{}", Self::rust_ident(&iface_name));
            let _ = writeln!(self.out, "        pub trait {trait_name} {{");
            for function in interface.functions.values() {
                let mut method_params = Vec::new();
                for param in &function.params {
                    method_params.push(format!(
                        "{}: {}",
                        Self::sanitize_field(&param.name),
                        self.rust_type(&param.ty)
                    ));
                }
                let params = method_params.join(", ");
                let result_ty = match &function.result {
                    Some(ty) => self.rust_type(ty),
                    None => "()".to_owned(),
                };
                let method_name = match &function.kind {
                    FunctionKind::Method(resource) => {
                        let resource_name = self.resolve.types[*resource]
                            .name
                            .as_deref()
                            .expect("resource name")
                            .replace('-', "_");
                        format!(
                            "{}_{}",
                            resource_name,
                            function.item_name().replace('-', "_")
                        )
                    }
                    _ => function.item_name().replace('-', "_"),
                };
                let _ = writeln!(
                    self.out,
                    "            fn {method_name}(&mut self, {params}) -> Result<{result_ty}, String>;",
                );
            }
            for (resource_name, resource_id) in &interface.types {
                if !matches!(self.resolve.types[*resource_id].kind, TypeDefKind::Resource) {
                    continue;
                }
                let drop_method = format!("drop_{}", resource_name.replace('-', "_"));
                let _ = writeln!(
                    self.out,
                    "            fn {drop_method}(&mut self, _handle: u32) -> Result<(), String> {{ Ok(()) }}"
                );
            }
            let _ = writeln!(self.out, "        }}");
        }
        let _ = writeln!(self.out);
        let package_id = self.resolve.worlds[self.world]
            .package
            .expect("world package");
        for (_, interface) in &imports {
            let iface_name = interface.name.clone().expect("interface name");
            let trait_name = format!("Host{}", Self::rust_ident(&iface_name));
            let module_name = {
                let package = &self.resolve.packages[package_id].name;
                let version = package.version.as_ref().expect("package version");
                format!(
                    "{}:{}/{}@{}.{}.{}",
                    package.namespace,
                    package.name,
                    iface_name,
                    version.major,
                    version.minor,
                    version.patch
                )
            };
            if interface.functions.is_empty()
                && !interface.types.values().any(|resource_id| {
                    matches!(self.resolve.types[*resource_id].kind, TypeDefKind::Resource)
                })
            {
                continue;
            }
            let add_name = format!("add_imports_{}", iface_name.replace('-', "_"));
            let _ = writeln!(
                self.out,
                "        pub fn {add_name}<T>(linker: &mut Linker<T>) -> anyhow::Result<()>\n        where T: {trait_name} + 'static,"
            );
            let _ = writeln!(self.out, "        {{");
            for function in interface.functions.values() {
                self.emit_import_trampoline(&module_name, &iface_name, function, &trait_name);
            }
            for (resource_name, resource_id) in &interface.types {
                if !matches!(self.resolve.types[*resource_id].kind, TypeDefKind::Resource) {
                    continue;
                }
                let drop_name = format!("[resource-drop]{resource_name}");
                let drop_method = format!("drop_{}", resource_name.replace('-', "_"));
                let _ = writeln!(
                    self.out,
                    "            linker.func_wrap({module_name:?}, {drop_name:?},\n                |mut caller: Caller<'_, T>, handle: i32| -> anyhow::Result<()> {{"
                );
                let _ = writeln!(
                    self.out,
                    "                    <T as {trait_name}>::{drop_method}(caller.as_context_mut().data_mut(), handle as u32).map_err(|error| trap(format!(\"{{}}::{{}} failed: {{error}}\", {module_name:?}, {drop_name:?})))?;"
                );
                let _ = writeln!(
                    self.out,
                    "                    Ok(())\n                }})?;"
                );
            }
            let _ = writeln!(self.out, "            Ok(())\n        }}");
            let _ = writeln!(self.out);
        }
        // Aggregate registration for every imported interface.
        {
            let all_traits = imports
                .iter()
                .map(|(_, interface)| {
                    format!(
                        "Host{}",
                        Self::rust_ident(&interface.name.clone().expect("interface name"))
                    )
                })
                .collect::<Vec<_>>()
                .join(" + ");
            let _ = writeln!(
                self.out,
                "        pub fn add_all_imports<T>(linker: &mut Linker<T>) -> anyhow::Result<()>\n        where T: {all_traits} + 'static,"
            );
            let _ = writeln!(self.out, "        {{");
            for (_, interface) in &imports {
                let has_imports = !interface.functions.is_empty()
                    || interface.types.values().any(|resource_id| {
                        matches!(self.resolve.types[*resource_id].kind, TypeDefKind::Resource)
                    });
                if has_imports {
                    let iface_name = interface.name.clone().expect("interface name");
                    let _ = writeln!(
                        self.out,
                        "            add_imports_{}(linker)?;",
                        iface_name.replace('-', "_")
                    );
                }
            }
            let _ = writeln!(self.out, "            Ok(())\n        }}");
            let _ = writeln!(self.out);
        }
        // Default-denied host: implements every imported interface trait and
        // rejects every operation. Lets a store instantiate any guest and
        // exercise lifecycle exports without granting capabilities.
        let _ = writeln!(self.out, "        pub struct DeniedHost {{");
        let _ = writeln!(self.out, "            pub wasi: WasiP1Ctx,");
        let _ = writeln!(self.out, "        }}");
        for (_, interface) in &imports {
            let iface_name = interface.name.clone().expect("interface name");
            let trait_name = format!("Host{}", Self::rust_ident(&iface_name));
            let _ = writeln!(self.out, "        impl {trait_name} for DeniedHost {{");
            for function in interface.functions.values() {
                let mut method_params = Vec::new();
                let mut param_names = Vec::new();
                for param in &function.params {
                    method_params.push(format!(
                        "{}: {}",
                        Self::sanitize_field(&param.name),
                        self.rust_type(&param.ty)
                    ));
                    param_names.push(Self::sanitize_field(&param.name));
                }
                let params = method_params.join(", ");
                let result_ty = match &function.result {
                    Some(ty) => self.rust_type(ty),
                    None => "()".to_owned(),
                };
                let method_name = match &function.kind {
                    FunctionKind::Method(resource) => {
                        let resource_name = self.resolve.types[*resource]
                            .name
                            .as_deref()
                            .expect("resource name")
                            .replace('-', "_");
                        format!(
                            "{}_{}",
                            resource_name,
                            function.item_name().replace('-', "_")
                        )
                    }
                    _ => function.item_name().replace('-', "_"),
                };
                let _ = writeln!(
                    self.out,
                    "            fn {method_name}(&mut self, {params}) -> Result<{result_ty}, String> {{"
                );
                let _ = writeln!(
                    self.out,
                    "                let _ = ({});",
                    param_names.join(", ")
                );
                let denied = match &function.result {
                    Some(Type::Id(result_id)) => match &self.resolve.types[*result_id].kind {
                        TypeDefKind::Result(result) => match &result.err {
                            Some(Type::Id(err_id)) => {
                                let mut current = *err_id;
                                let is_enum = loop {
                                    match &self.resolve.types[current].kind {
                                        TypeDefKind::Enum(_) => break true,
                                        TypeDefKind::Type(Type::Id(next)) => current = *next,
                                        _ => break false,
                                    }
                                };
                                if is_enum {
                                    let err_ty = self.rust_type(&Type::Id(current));
                                    format!("Ok(Err({err_ty}::Denied))")
                                } else {
                                    "Ok(Err(\"denied by default policy\".to_owned()))".to_owned()
                                }
                            }
                            _ => "Ok(Err(\"denied by default policy\".to_owned()))".to_owned(),
                        },
                        _ => "Err(\"denied by default policy\".to_owned())".to_owned(),
                    },
                    _ => "Err(\"denied by default policy\".to_owned())".to_owned(),
                };
                let _ = writeln!(self.out, "                {denied}");
                let _ = writeln!(self.out, "            }}");
            }
            let _ = writeln!(self.out, "        }}");
        }
        let _ = writeln!(self.out, "    }}");
    }

    fn emit_import_trampoline(
        &mut self,
        module_name: &str,
        _iface_name: &str,
        function: &Function,
        trait_name: &str,
    ) {
        let signature = self
            .resolve
            .wasm_signature(AbiVariant::GuestImport, function);
        let flat_count = signature.params.len();
        let mut bindgen = host_import::HostImportBindgen::new(
            &self.resolve,
            &self.sizes,
            trait_name,
            module_name,
            function,
            flat_count,
        );
        wit_bindgen_core::abi::call(
            &self.resolve,
            AbiVariant::GuestImport,
            wit_bindgen_core::abi::LiftLower::LiftArgsLowerResults,
            function,
            &mut bindgen,
            false,
        );
        let params = signature
            .params
            .iter()
            .enumerate()
            .map(|(index, ty)| format!("arg{index}: {}", Self::wasm_ty_name(ty)))
            .collect::<Vec<_>>()
            .join(", ");
        let ret_ty = if signature.retptr || signature.results.is_empty() {
            "()".to_owned()
        } else {
            signature
                .results
                .iter()
                .map(Self::wasm_ty_name)
                .collect::<Vec<_>>()
                .join(", ")
        };
        let _ = writeln!(
            self.out,
            "            linker.func_wrap({module_name:?}, {:?},
                |mut caller: Caller<'_, T>, {}| -> anyhow::Result<{ret_ty}> {{",
            function.name, params
        );
        let _ = writeln!(
            self.out,
            "                    let mem = mem_of(&mut caller)?;"
        );
        let _ = writeln!(self.out, "{}", bindgen.out);
        let _ = writeln!(self.out, "                }})?;");
    }

    fn tmp(&mut self) -> usize {
        let tmp = self.tmp;
        self.tmp += 1;
        tmp
    }

    fn size_of(&self, ty: &Type) -> usize {
        self.sizes.size(ty).size_wasm32()
    }

    fn flat_count(&self, ty: &Type) -> usize {
        let mut buf = [wit_parser::abi::WasmType::I32; 64];
        let mut flats = wit_parser::abi::FlatTypes::new(&mut buf);
        let _ = self.resolve.push_flat(ty, &mut flats);
        flats.to_vec().len()
    }

    fn align_of(&self, ty: &Type) -> usize {
        self.sizes.align(ty).align_wasm32()
    }

    fn bind(&mut self, expression: String) -> String {
        let tmp = self.tmp;
        self.tmp += 1;
        let name = format!("t{tmp}");
        let _ = writeln!(self.out, "let {name} = {expression};");
        name
    }

    /// Generates code that lowers one WIT parameter `value` (a Rust
    /// expression) into its flat wasm argument expressions. Side effects
    /// (allocations, memory writes) are emitted into the current output block.
    /// `indirect` forces a memory-backed lowering even when the flat count is
    /// small (used by the packed indirect-parameter path).
    fn emit_param_flat(&mut self, ty: &Type, value: &str, indirect: bool) -> Vec<String> {
        match ty {
            Type::Bool => vec![format!("if {value} {{ 1 }} else {{ 0 }}")],
            Type::U8
            | Type::U16
            | Type::U32
            | Type::S8
            | Type::S16
            | Type::S32
            | Type::Char
            | Type::ErrorContext => vec![format!("({value} as i32)")],
            Type::U64 | Type::S64 => vec![format!("({value} as i64)")],
            Type::F32 => vec![format!("({value} as f32)")],
            Type::F64 => vec![format!("({value} as f64)")],
            Type::String => {
                let ptr = self.bind(format!("alloc_s(store, instance, &mem, {value}.len(), 1)?"));
                self.emit_statement(format!(
                    "mem.data_mut(store.as_context_mut()).get_mut({ptr} as usize..).and_then(|s| s.get_mut(..{value}.len())).ok_or_else(|| trap(\"allocation out of bounds\"))?.copy_from_slice({value}.as_bytes());"
                ));
                vec![ptr, format!("{value}.len() as i32")]
            }
            Type::Id(id) => {
                let kind = self.resolve.types[*id].kind.clone();
                match &kind {
                    TypeDefKind::Type(inner) => self.emit_param_flat(inner, value, indirect),
                    TypeDefKind::Handle(_) => vec![format!("({value} as i32)")],
                    TypeDefKind::Enum(_) => vec![format!("({value} as i32)")],
                    TypeDefKind::List(inner) => {
                        if matches!(inner, Type::String) {
                            let ptr = self.bind(format!(
                                "lower_list_string_param_s(store, instance, &mem, &{value})?"
                            ));
                            vec![ptr, format!("{value}.len() as i32")]
                        } else if matches!(inner, Type::U8) {
                            let ptr = self
                                .bind(format!("alloc_s(store, instance, &mem, {value}.len(), 1)?"));
                            self.emit_statement(format!(
                                "mem.data_mut(store.as_context_mut()).get_mut({ptr} as usize..).and_then(|s| s.get_mut(..{value}.len())).ok_or_else(|| trap(\"allocation out of bounds\"))?.copy_from_slice({value}.as_slice());"
                            ));
                            vec![ptr, format!("{value}.len() as i32")]
                        } else {
                            // Allocate the element array and write each element.
                            let size = self.size_of(inner);
                            let align = self.align_of(inner);
                            let ptr = self.bind(format!(
                                "alloc_s(store, instance, &mem, {value}.len().checked_mul({size}).ok_or_else(|| trap(\"list size overflow\"))?, {align})?"
                            ));
                            let tmp = self.tmp();
                            let _ = writeln!(
                                self.out,
                                "for (i{tmp}, e) in {value}.iter().enumerate() {{"
                            );
                            let _ =
                                writeln!(self.out, "let base = {ptr} + (i{tmp} * {size}) as i32;");
                            self.emit_write_mem(inner, "e", "base", 0);
                            let _ = writeln!(self.out, "}}");
                            vec![ptr, format!("{value}.len() as i32")]
                        }
                    }
                    TypeDefKind::Record(record) => {
                        let flat = self.flat_count(ty);
                        if flat > 16 || indirect {
                            let size = self.size_of(ty);
                            let align = self.align_of(ty);
                            let ptr = self
                                .bind(format!("alloc_s(store, instance, &mem, {size}, {align})?"));
                            self.emit_write_mem(ty, value, &ptr, 0);
                            vec![ptr]
                        } else {
                            let mut flats = Vec::new();
                            for field in &record.fields {
                                flats.extend(self.emit_param_flat(
                                    &field.ty,
                                    &format!("{value}.{}", Self::sanitize_field(&field.name)),
                                    indirect,
                                ));
                            }
                            flats
                        }
                    }
                    TypeDefKind::Option(inner) => {
                        let tmp = self.tmp();
                        let payload_flats = if self.size_of(inner) > 0 {
                            self.flat_count(inner)
                        } else {
                            0
                        };
                        let _ = writeln!(self.out, "let v{tmp} = match {value} {{");
                        let _ = writeln!(self.out, "    Some(e) => {{");
                        let mut flats = vec!["1".to_owned()];
                        if payload_flats > 0 {
                            flats.extend(self.emit_param_flat(inner, "e", false));
                        }
                        for _ in flats.len()..(1 + payload_flats) {
                            flats.push("0".to_owned());
                        }
                        let _ = writeln!(self.out, "        ({})", flats.join(", "));
                        let _ = writeln!(self.out, "    }}");
                        let _ = writeln!(self.out, "    None => {{");
                        let none = vec!["0".to_owned(); 1 + payload_flats];
                        let _ = writeln!(self.out, "        ({})", none.join(", "));
                        let _ = writeln!(self.out, "    }}");
                        let _ = writeln!(self.out, "}};");
                        (0..(1 + payload_flats))
                            .map(|index| format!("v{tmp}.{index}"))
                            .collect()
                    }
                    TypeDefKind::Result(result) => {
                        let tmp = self.tmp();
                        let ok_flats = result
                            .ok
                            .as_ref()
                            .map(|ok| self.flat_count(ok))
                            .unwrap_or(0);
                        let err_flats = result
                            .err
                            .as_ref()
                            .map(|err| self.flat_count(err))
                            .unwrap_or(0);
                        let width = 1 + ok_flats.max(err_flats);
                        let _ = writeln!(self.out, "let v{tmp} = match {value} {{");
                        let _ = writeln!(self.out, "    Ok(e) => {{");
                        let mut flats = vec!["0".to_owned()];
                        if ok_flats > 0 {
                            flats.extend(self.emit_param_flat(
                                result.ok.as_ref().unwrap(),
                                "e",
                                false,
                            ));
                        }
                        for _ in flats.len()..width {
                            flats.push("0".to_owned());
                        }
                        let _ = writeln!(self.out, "        ({})", flats.join(", "));
                        let _ = writeln!(self.out, "    }}");
                        let _ = writeln!(self.out, "    Err(e) => {{");
                        let mut flats = vec!["1".to_owned()];
                        if err_flats > 0 {
                            flats.extend(self.emit_param_flat(
                                result.err.as_ref().unwrap(),
                                "e",
                                false,
                            ));
                        }
                        for _ in flats.len()..width {
                            flats.push("0".to_owned());
                        }
                        let _ = writeln!(self.out, "        ({})", flats.join(", "));
                        let _ = writeln!(self.out, "    }}");
                        let _ = writeln!(self.out, "}};");
                        (0..width).map(|index| format!("v{tmp}.{index}")).collect()
                    }
                    TypeDefKind::Variant(variant) => {
                        let tmp = self.tmp();
                        let enum_name = self.type_rust_name(*id);
                        let widths: Vec<usize> = variant
                            .cases
                            .iter()
                            .map(|case| case.ty.as_ref().map(|ty| self.flat_count(ty)).unwrap_or(0))
                            .collect();
                        let width = 1 + widths.iter().copied().max().unwrap_or(0);
                        let _ = writeln!(self.out, "let v{tmp} = match {value} {{");
                        for (index, (case, case_width)) in
                            variant.cases.iter().zip(&widths).enumerate()
                        {
                            let case_name = Self::rust_ident(&case.name);
                            let _ = writeln!(self.out, "    {enum_name}::{case_name}(e) => {{");
                            let mut flats = vec![index.to_string()];
                            if *case_width > 0 {
                                flats.extend(self.emit_param_flat(
                                    case.ty.as_ref().unwrap(),
                                    "e",
                                    false,
                                ));
                            }
                            for _ in flats.len()..width {
                                flats.push("0".to_owned());
                            }
                            let _ = writeln!(self.out, "        ({})", flats.join(", "));
                            let _ = writeln!(self.out, "    }}");
                        }
                        let _ = writeln!(
                            self.out,
                            "    _ => return Err(anyhow::anyhow!(\"unsupported variant case\")),"
                        );
                        let _ = writeln!(self.out, "}};");
                        (0..width).map(|index| format!("v{tmp}.{index}")).collect()
                    }
                    _ => {
                        let _ = writeln!(
                            self.out,
                            "return Err(anyhow::anyhow!(\"unsupported parameter type\"));"
                        );
                        vec![]
                    }
                }
            }
        }
    }

    /// Generates code that writes `value` (a Rust expression) into guest
    /// memory at `base` plus `offset` (canonical ABI layout).
    fn emit_write_mem(&mut self, ty: &Type, value: &str, base: &str, offset: usize) {
        match ty {
            Type::Bool => {
                self.emit_statement(format!(
                    "write_i32_at_s(store, &mem, {base}, {offset}, if {value} {{ 1 }} else {{ 0 }})?;"
                ));
            }
            Type::U8
            | Type::U16
            | Type::U32
            | Type::S8
            | Type::S16
            | Type::S32
            | Type::Char
            | Type::ErrorContext => {
                self.emit_statement(format!(
                    "write_i32_at_s(store, &mem, {base}, {offset}, {value} as i32)?;"
                ));
            }
            Type::U64 | Type::S64 => {
                self.emit_statement(format!(
                    "write_i64_at_s(store, &mem, {base}, {offset}, {value} as i64)?;"
                ));
            }
            Type::F32 => {
                self.emit_statement(format!(
                    "write_f32_at_s(store, &mem, {base}, {offset}, {value})?;"
                ));
            }
            Type::F64 => {
                self.emit_statement(format!(
                    "write_f64_at_s(store, &mem, {base}, {offset}, {value})?;"
                ));
            }
            Type::String => {
                self.emit_statement(format!(
                    "write_string_at_s(store, instance, &mem, {base}, {offset}, &{value})?;"
                ));
            }
            Type::Id(id) => {
                let kind = self.resolve.types[*id].kind.clone();
                match &kind {
                    TypeDefKind::Type(inner) => self.emit_write_mem(inner, value, base, offset),
                    TypeDefKind::Handle(_) => {
                        self.emit_statement(format!(
                            "write_i32_at_s(store, &mem, {base}, {offset}, {value} as i32)?;"
                        ));
                    }
                    TypeDefKind::Enum(_) => {
                        self.emit_statement(format!(
                            "write_i32_at_s(store, &mem, {base}, {offset}, {value} as i32)?;"
                        ));
                    }
                    TypeDefKind::List(inner) => {
                        if matches!(inner, Type::String) {
                            self.emit_statement(format!(
                                "write_list_string_at_s(store, instance, &mem, {base}, {offset}, &{value})?;"
                            ));
                        } else if matches!(inner, Type::U8) {
                            let ptr = self
                                .bind(format!("alloc_s(store, instance, &mem, {value}.len(), 1)?"));
                            self.emit_statement(format!(
                                "mem.data_mut(store.as_context_mut()).get_mut({ptr} as usize..).and_then(|s| s.get_mut(..{value}.len())).ok_or_else(|| trap(\"allocation out of bounds\"))?.copy_from_slice({value}.as_slice());"
                            ));
                            self.emit_statement(format!(
                                "write_i32_at_s(store, &mem, {base}, {offset}, {ptr})?;"
                            ));
                            self.emit_statement(format!(
                                "write_i32_at_s(store, &mem, {base}, {offset} + 4, {value}.len() as i32)?;"
                            ));
                        } else {
                            let size = self.size_of(inner);
                            let ptr = self.bind(format!(
                                "alloc_s(store, instance, &mem, {value}.len().checked_mul({size}).ok_or_else(|| trap(\"list size overflow\"))?, {})?",
                                self.align_of(inner)
                            ));
                            let tmp = self.tmp();
                            let _ = writeln!(
                                self.out,
                                "for (i{tmp}, e) in {value}.iter().enumerate() {{"
                            );
                            let _ =
                                writeln!(self.out, "let base = {ptr} + (i{tmp} * {size}) as i32;");
                            self.emit_write_mem(inner, "e", "base", 0);
                            let _ = writeln!(self.out, "}}");
                            self.emit_statement(format!(
                                "write_i32_at_s(store, &mem, {base}, {offset}, {ptr})?;"
                            ));
                            self.emit_statement(format!(
                                "write_i32_at_s(store, &mem, {base}, {offset} + 4, {value}.len() as i32)?;"
                            ));
                        }
                    }
                    TypeDefKind::Record(record) => {
                        let mut field_offset = 0usize;
                        for field in &record.fields {
                            field_offset = self.align_up(field_offset, self.align_of(&field.ty));
                            self.emit_write_mem(
                                &field.ty,
                                &format!("{value}.{}", Self::sanitize_field(&field.name)),
                                base,
                                offset + field_offset,
                            );
                            field_offset += self.size_of(&field.ty);
                        }
                    }
                    TypeDefKind::Option(inner) => {
                        let _ = writeln!(self.out, "match &{value} {{");
                        let _ = writeln!(self.out, "    Some(e) => {{");
                        self.emit_statement(format!(
                            "write_i32_at_s(store, &mem, {base}, {offset}, 1)?;"
                        ));
                        if self.size_of(inner) > 0 {
                            let payload_offset = self.align_up(4, self.align_of(inner));
                            self.emit_write_mem(inner, "e", base, offset + payload_offset);
                        }
                        let _ = writeln!(self.out, "    }}");
                        let _ = writeln!(self.out, "    None => {{");
                        self.emit_statement(format!(
                            "write_i32_at_s(store, &mem, {base}, {offset}, 0)?;"
                        ));
                        let _ = writeln!(self.out, "    }}");
                        let _ = writeln!(self.out, "}};");
                    }
                    TypeDefKind::Result(result) => {
                        let _ = writeln!(self.out, "match &{value} {{");
                        let _ = writeln!(self.out, "    Ok(e) => {{");
                        self.emit_statement(format!(
                            "write_i32_at_s(store, &mem, {base}, {offset}, 0)?;"
                        ));
                        if let Some(ok) = &result.ok
                            && self.size_of(ok) > 0
                        {
                            let payload_offset = self.align_up(4, self.align_of(ok));
                            self.emit_write_mem(ok, "e", base, offset + payload_offset);
                        }
                        let _ = writeln!(self.out, "    }}");
                        let _ = writeln!(self.out, "    Err(e) => {{");
                        self.emit_statement(format!(
                            "write_i32_at_s(store, &mem, {base}, {offset}, 1)?;"
                        ));
                        if let Some(err) = &result.err
                            && self.size_of(err) > 0
                        {
                            let payload_offset = self.align_up(4, self.align_of(err));
                            self.emit_write_mem(err, "e", base, offset + payload_offset);
                        }
                        let _ = writeln!(self.out, "    }}");
                        let _ = writeln!(self.out, "}};");
                    }
                    TypeDefKind::Variant(variant) => {
                        let _ = writeln!(self.out, "match &{value} {{");
                        for (index, case) in variant.cases.iter().enumerate() {
                            let case_name = Self::rust_ident(&case.name);
                            let _ = writeln!(self.out, "    {case_name}(e) => {{");
                            self.emit_statement(format!(
                                "write_i32_at_s(store, &mem, {base}, {offset}, {index})?;"
                            ));
                            if let Some(ty) = &case.ty
                                && self.size_of(ty) > 0
                            {
                                let payload_offset = self.align_up(4, self.align_of(ty));
                                self.emit_write_mem(ty, "e", base, offset + payload_offset);
                            }
                            let _ = writeln!(self.out, "    }}");
                        }
                        let _ = writeln!(
                            self.out,
                            "_ => return Err(anyhow::anyhow!(\"unsupported variant case\")),"
                        );
                        let _ = writeln!(self.out, "}};");
                    }
                    _ => {
                        let _ = writeln!(
                            self.out,
                            "return Err(anyhow::anyhow!(\"unsupported write type\"));"
                        );
                    }
                }
            }
        }
    }

    fn emit_statement(&mut self, statement: String) {
        let _ = writeln!(self.out, "{statement}");
    }

    /// Generates code that reads a value of `ty` from guest memory at `base`
    /// (an i32 expression) plus `offset`, binding it to a fresh variable and
    /// returning that variable name. Used to lift guest-export results from
    /// their return area.
    fn emit_read_result(&mut self, ty: &Type, base: &str, offset: usize) -> String {
        match ty {
            Type::Bool => self.bind(format!(
                "read_i32_at_s(store, &mem, {base}, {offset})? != 0"
            )),
            Type::U8 => self.bind(format!(
                "read_i32_at_s(store, &mem, {base}, {offset})? as u8"
            )),
            Type::S8 => self.bind(format!(
                "read_i32_at_s(store, &mem, {base}, {offset})? as i8"
            )),
            Type::U16 => self.bind(format!(
                "read_i32_at_s(store, &mem, {base}, {offset})? as u16"
            )),
            Type::S16 => self.bind(format!(
                "read_i32_at_s(store, &mem, {base}, {offset})? as i16"
            )),
            Type::U32 | Type::Char => self.bind(format!(
                "read_i32_at_s(store, &mem, {base}, {offset})? as u32"
            )),
            Type::S32 => self.bind(format!("read_i32_at_s(store, &mem, {base}, {offset})?")),
            Type::U64 => self.bind(format!(
                "read_i64_at_s(store, &mem, {base}, {offset})? as u64"
            )),
            Type::S64 => self.bind(format!("read_i64_at_s(store, &mem, {base}, {offset})?")),
            Type::F32 => self.bind(format!("read_f32_at_s(store, &mem, {base}, {offset})?")),
            Type::F64 => self.bind(format!("read_f64_at_s(store, &mem, {base}, {offset})?")),
            Type::ErrorContext => self.bind(format!(
                "read_i32_at_s(store, &mem, {base}, {offset})? as u32"
            )),
            Type::String => self.bind(format!("lift_string_at_s(store, &mem, {base}, {offset})?")),
            Type::Id(id) => {
                let kind = self.resolve.types[*id].kind.clone();
                match &kind {
                    TypeDefKind::Type(inner) => self.emit_read_result(inner, base, offset),
                    TypeDefKind::Handle(_) => self.bind(format!(
                        "read_i32_at_s(store, &mem, {base}, {offset})? as u32"
                    )),
                    TypeDefKind::Enum(enum_) => {
                        let tag =
                            self.bind(format!("read_i32_at_s(store, &mem, {base}, {offset})?"));
                        let tmp = self.tmp();
                        let enum_name = self.type_rust_name(*id);
                        let _ = writeln!(self.out, "let e{tmp} = match {tag} {{");
                        for (index, case) in enum_.cases.iter().enumerate() {
                            let case_name = Self::rust_ident(&case.name);
                            let _ = writeln!(self.out, "    {index} => {enum_name}::{case_name},");
                        }
                        let _ = writeln!(
                            self.out,
                            "    _ => return Err(trap(\"invalid enum discriminant\")),"
                        );
                        let _ = writeln!(self.out, "}};");
                        format!("e{tmp}")
                    }
                    TypeDefKind::List(inner) => {
                        if matches!(inner, Type::String) {
                            self.bind(format!(
                                "lift_list_string_at_s(store, &mem, {base}, {offset})?"
                            ))
                        } else {
                            let ptr =
                                self.bind(format!("read_i32_at_s(store, &mem, {base}, {offset})?"));
                            let len = self
                                .bind(format!("read_i32_at_s(store, &mem, {base}, {offset} + 4)?"));
                            let tmp = self.tmp();
                            let size = self.size_of(inner);
                            let element = self.rust_type(inner);
                            let _ = writeln!(
                                self.out,
                                "let mut vec{tmp}: Vec<{element}> = Vec::with_capacity({len} as usize);"
                            );
                            let _ = writeln!(self.out, "for i{tmp} in 0..{len} {{");
                            let _ = writeln!(self.out, "let base = {ptr} + i{tmp} * {size};");
                            let value = self.emit_read_result(inner, "base", 0);
                            let _ = writeln!(self.out, "vec{tmp}.push({value});");
                            let _ = writeln!(self.out, "}}");
                            format!("vec{tmp}")
                        }
                    }
                    TypeDefKind::Option(inner) => {
                        let tag =
                            self.bind(format!("read_i32_at_s(store, &mem, {base}, {offset})?"));
                        let tmp = self.tmp();
                        if self.size_of(inner) > 0 {
                            let payload_offset = self.align_up(4, self.align_of(inner));
                            let value = self.emit_read_result(inner, base, offset + payload_offset);
                            let _ = writeln!(
                                self.out,
                                "let v{tmp} = if {tag} != 0 {{ Some({value}) }} else {{ None }};"
                            );
                        } else {
                            let _ = writeln!(
                                self.out,
                                "let v{tmp} = if {tag} != 0 {{ Some(()) }} else {{ None }};"
                            );
                        }
                        format!("v{tmp}")
                    }
                    TypeDefKind::Result(result) => {
                        let tag =
                            self.bind(format!("read_i32_at_s(store, &mem, {base}, {offset})?"));
                        let tmp = self.tmp();
                        let _ = writeln!(self.out, "let v{tmp} = if {tag} == 0 {{");
                        match &result.ok {
                            Some(ok) if self.size_of(ok) > 0 => {
                                let payload_offset = self.align_up(4, self.align_of(ok));
                                let value =
                                    self.emit_read_result(ok, base, offset + payload_offset);
                                let _ = writeln!(self.out, "Ok({value})");
                            }
                            _ => {
                                let _ = writeln!(self.out, "Ok(())");
                            }
                        }
                        let _ = writeln!(self.out, "}} else {{");
                        match &result.err {
                            Some(err) if self.size_of(err) > 0 => {
                                let payload_offset = self.align_up(4, self.align_of(err));
                                let value =
                                    self.emit_read_result(err, base, offset + payload_offset);
                                let _ = writeln!(self.out, "Err({value})");
                            }
                            _ => {
                                let _ = writeln!(self.out, "Err(())");
                            }
                        }
                        let _ = writeln!(self.out, "}};");
                        format!("v{tmp}")
                    }
                    TypeDefKind::Record(record) => {
                        let mut field_offset = 0usize;
                        let mut fields = Vec::new();
                        for field in &record.fields {
                            field_offset = self.align_up(field_offset, self.align_of(&field.ty));
                            let value =
                                self.emit_read_result(&field.ty, base, offset + field_offset);
                            fields.push(format!("{}: {value}", Self::sanitize_field(&field.name)));
                            field_offset += self.size_of(&field.ty);
                        }
                        let name = self.type_rust_name(*id);
                        self.bind(format!("{name} {{ {} }}", fields.join(", ")))
                    }
                    TypeDefKind::Variant(variant) => {
                        let tag =
                            self.bind(format!("read_i32_at_s(store, &mem, {base}, {offset})?"));
                        let tmp = self.tmp();
                        let enum_name = self.type_rust_name(*id);
                        let _ = writeln!(self.out, "let v{tmp} = match {tag} {{");
                        for (index, case) in variant.cases.iter().enumerate() {
                            let case_name = Self::rust_ident(&case.name);
                            match &case.ty {
                                Some(ty) if self.size_of(ty) > 0 => {
                                    let payload_offset = self.align_up(4, self.align_of(ty));
                                    let _ = writeln!(self.out, "    {index} => {{");
                                    let value =
                                        self.emit_read_result(ty, base, offset + payload_offset);
                                    let _ = writeln!(
                                        self.out,
                                        "        {enum_name}::{case_name}({value})"
                                    );
                                    let _ = writeln!(self.out, "    }},");
                                }
                                _ => {
                                    let _ = writeln!(
                                        self.out,
                                        "    {index} => {enum_name}::{case_name},"
                                    );
                                }
                            }
                        }
                        let _ = writeln!(
                            self.out,
                            "    _ => return Err(trap(\"invalid variant discriminant\")),"
                        );
                        let _ = writeln!(self.out, "}};");
                        format!("v{tmp}")
                    }
                    _ => {
                        let _ =
                            writeln!(self.out, "return Err(trap(\"unsupported result type\"));");
                        "()".to_owned()
                    }
                }
            }
        }
    }

    fn align_up(&self, value: usize, align: usize) -> usize {
        if align <= 1 {
            value
        } else {
            value.div_ceil(align) * align
        }
    }

    fn emit_exports(&mut self) {
        let mut exports: Vec<(String, Interface)> = Vec::new();
        let mut freestanding: Vec<(String, Function)> = Vec::new();
        for (name, item) in self.resolve.worlds[self.world].exports.iter() {
            match item {
                WorldItem::Interface { id, .. } => {
                    exports.push((name.clone().into(), self.resolve.interfaces[*id].clone()));
                }
                WorldItem::Function(function) => {
                    freestanding.push((name.clone().into(), function.clone()));
                }
                WorldItem::Type { .. } => {}
            }
        }
        if exports.is_empty() && freestanding.is_empty() {
            return;
        }
        let _ = writeln!(self.out, "    pub struct CoreExports {{");
        for (name, function) in &freestanding {
            let field = Self::sanitize_field(name);
            let call_ty = if function.result.is_some() {
                "(), i32"
            } else {
                "(), ()"
            };
            let _ = writeln!(
                self.out,
                "        pub {field}: Option<wasmtime::TypedFunc<{call_ty}>>,"
            );
            let _ = writeln!(
                self.out,
                "        pub {field}_post: Option<wasmtime::TypedFunc<i32, ()>>,"
            );
        }
        for (_, interface) in &exports {
            for function in interface.functions.values() {
                let name = Self::export_field_name(interface, function);
                let signature = self
                    .resolve
                    .wasm_signature(AbiVariant::GuestExport, function);
                let flat = signature
                    .params
                    .iter()
                    .map(|ty| Self::wasm_ty_name(ty))
                    .collect::<Vec<_>>()
                    .join(", ");
                let result_ty = if signature.retptr {
                    "i32".to_owned()
                } else if signature.results.is_empty() {
                    "()".to_owned()
                } else {
                    "i32".to_owned()
                };
                let _ = writeln!(
                    self.out,
                    "        {name}: Option<wasmtime::TypedFunc<({flat}), {result_ty}>>,"
                );
                if signature.retptr {
                    let _ = writeln!(
                        self.out,
                        "        pub {name}_post: Option<wasmtime::TypedFunc<i32, ()>>,"
                    );
                }
            }
        }
        let _ = writeln!(self.out, "    }}");
        let _ = writeln!(self.out);
        let _ = writeln!(
            self.out,
            "    impl CoreExports {{\n        pub fn new<T: AsContextMut>(instance: &Instance, mut store: T) -> Result<Self, String> {{"
        );
        let _ = writeln!(self.out, "        Ok(Self {{");
        for (name, function) in &freestanding {
            let field = Self::sanitize_field(name);
            let (call_ty, post_ty) = if function.result.is_some() {
                ("(), i32", "i32, ()")
            } else {
                ("(), ()", "i32, ()")
            };
            let _ = writeln!(
                self.out,
                "            {field}: instance.get_typed_func::<{call_ty}>(&mut store, {name:?}).ok(),",
            );
            let _ = writeln!(
                self.out,
                "            {field}_post: instance.get_typed_func::<{post_ty}>(&mut store, \"cabi_post_{name}\").ok(),",
            );
        }
        for (_, interface) in &exports {
            for function in interface.functions.values() {
                let name = Self::export_field_name(interface, function);
                let export_name = self.export_core_name(interface, function);
                let signature = self
                    .resolve
                    .wasm_signature(AbiVariant::GuestExport, function);
                let flat = signature
                    .params
                    .iter()
                    .map(|ty| Self::wasm_ty_name(ty))
                    .collect::<Vec<_>>()
                    .join(", ");
                let result_ty = if signature.retptr {
                    "i32".to_owned()
                } else if signature.results.is_empty() {
                    "()".to_owned()
                } else {
                    "i32".to_owned()
                };
                let _ = writeln!(
                    self.out,
                    "            {name}: instance.get_typed_func::<({flat}), {result_ty}>(&mut store, {export_name:?}).ok(),",
                );
                if signature.retptr {
                    let _ = writeln!(
                        self.out,
                        "            {name}_post: instance.get_typed_func::<i32, ()>(&mut store, \"cabi_post_{export_name}\").ok(),",
                    );
                }
            }
        }
        let _ = writeln!(self.out, "        }})\n        }}");
        for (name, function) in &freestanding {
            let field = Self::sanitize_field(name);
            match &function.result {
                Some(ty) => {
                    let result_ty = self.rust_type(ty);
                    let _ = writeln!(
                        self.out,
                        "        pub fn call_{field}<T>(&self, instance: &Instance, store: &mut Store<T>) -> anyhow::Result<{result_ty}> {{"
                    );
                    let _ = writeln!(
                        self.out,
                        "            let func = self.{field}.as_ref().ok_or_else(|| anyhow::anyhow!(\"missing {name} export\"))?;"
                    );
                    let _ = writeln!(
                        self.out,
                        "            let retptr = func.call(&mut *store, ())?;"
                    );
                    let _ = writeln!(
                        self.out,
                        "            let mem = instance.get_export(&mut *store, \"memory\").and_then(|export| export.into_memory()).ok_or_else(|| anyhow::anyhow!(\"missing memory export\"))?;"
                    );
                    let value = self.emit_read_result(ty, "retptr", 0);
                    let _ = writeln!(
                        self.out,
                        "            if let Some(post) = &self.{field}_post {{ post.call(&mut *store, retptr)?; }}"
                    );
                    let _ = writeln!(self.out, "            Ok({value})");
                    let _ = writeln!(self.out, "        }}");
                }
                None => {
                    let _ = writeln!(
                        self.out,
                        "        pub fn call_{field}<T>(&self, store: &mut Store<T>) -> anyhow::Result<()> {{"
                    );
                    let _ = writeln!(
                        self.out,
                        "            let func = self.{field}.as_ref().ok_or_else(|| anyhow::anyhow!(\"missing {name} export\"))?;"
                    );
                    let _ = writeln!(self.out, "            func.call(&mut *store, ())?;");
                    let _ = writeln!(self.out, "            Ok(())");
                    let _ = writeln!(self.out, "        }}");
                }
            }
        }
        for (_, interface) in &exports {
            for function in interface.functions.values() {
                self.emit_interface_call_method(interface, function);
            }
        }
        let _ = writeln!(self.out, "    }}");
    }

    fn emit_interface_call_method(&mut self, interface: &Interface, function: &Function) {
        self.emit_call_method_variant(interface, function, ExportCallVariant::Store);
        self.emit_call_method_variant(interface, function, ExportCallVariant::Caller);
    }

    /// Emits one `CoreExports` call method for either a store or its live
    /// caller. The selected context determines how generated code accesses
    /// the underlying store.
    fn emit_call_method_variant(
        &mut self,
        interface: &Interface,
        function: &Function,
        variant: ExportCallVariant,
    ) {
        let (name_template, store_param, store_ident, store_expr, preamble) = match variant {
            ExportCallVariant::Store => (
                "call_{field}",
                "store: &mut Store<T>",
                "store",
                "&mut *store",
                "",
            ),
            ExportCallVariant::Caller => (
                "call_{field}_with_caller",
                "caller: &mut Caller<'_, T>",
                "store",
                "&mut *store",
                "            let mut store = &mut *caller;\n",
            ),
        };
        let field = Self::export_field_name(interface, function);
        let export_name = self.export_core_name(interface, function);
        let signature = self
            .resolve
            .wasm_signature(AbiVariant::GuestExport, function);
        let result_ty = match &function.result {
            Some(ty) => self.rust_type(ty),
            None => "()".to_owned(),
        };
        let mut method_params = Vec::new();
        let mut param_names = Vec::new();
        for param in &function.params {
            method_params.push(format!(
                "{}: {}",
                Self::sanitize_field(&param.name),
                self.rust_type(&param.ty)
            ));
            param_names.push(Self::sanitize_field(&param.name));
        }
        let params = method_params.join(", ");
        let name = name_template.replace("{field}", &field);
        let _ = writeln!(
            self.out,
            "        pub fn {name}<T>(&self, instance: &Instance, {store_param}, {params}) -> anyhow::Result<{result_ty}> {{"
        );
        if !preamble.is_empty() {
            let _ = writeln!(self.out, "{preamble}");
        }
        let _ = writeln!(
            self.out,
            "            let func = self.{field}.as_ref().ok_or_else(|| anyhow::anyhow!(\"missing {export_name} export\"))?;"
        );
        let _ = writeln!(
            self.out,
            "            let mem = instance.get_export({store_expr}, \"memory\").and_then(|export| export.into_memory()).ok_or_else(|| anyhow::anyhow!(\"missing memory export\"))?;"
        );
        // Lower parameters.
        let mut flat_args = Vec::new();
        if signature.indirect_params {
            let mut total = 0usize;
            let mut max_align = 1usize;
            for param in &function.params {
                let size = self.size_of(&param.ty);
                let align = self.align_of(&param.ty);
                total = self.align_up(total, align) + size;
                max_align = max_align.max(align);
            }
            let packed = self.bind(format!(
                "alloc_s({store_ident}, instance, &mem, {total}, {max_align})?"
            ));
            let mut offset = 0usize;
            for (param, name) in function.params.iter().zip(&param_names) {
                offset = self.align_up(offset, self.align_of(&param.ty));
                self.emit_write_mem(&param.ty, name, &packed, offset);
                offset += self.size_of(&param.ty);
            }
            flat_args.push(packed);
        } else {
            for (param, name) in function.params.iter().zip(&param_names) {
                flat_args.extend(self.emit_param_flat(&param.ty, name, false));
            }
        }
        let call = format!("func.call({store_expr}, ({}))", flat_args.join(", "));
        if let Some(result_ty) = &function.result {
            let retptr = self.bind(format!(
                "{call}.map_err(|error| anyhow::anyhow!(\"{export_name} failed: {{error}}\"))?"
            ));
            let value = self.emit_read_result(result_ty, &retptr, 0);
            let _ = writeln!(
                self.out,
                "            if let Some(post) = &self.{field}_post {{ post.call({store_expr}, {retptr}).map_err(|error| anyhow::anyhow!(\"cabi_post {export_name} failed: {{error}}\"))?; }}"
            );
            let _ = writeln!(self.out, "            Ok({value})");
        } else {
            let _ = writeln!(
                self.out,
                "            {call}.map_err(|error| anyhow::anyhow!(\"{export_name} failed: {{error}}\"))?;"
            );
            let _ = writeln!(self.out, "            Ok(())");
        }
        let _ = writeln!(self.out, "        }}");
    }

    fn export_field_name(interface: &Interface, function: &Function) -> String {
        let iface = interface.name.clone().expect("interface name");
        let item = function.item_name();
        let field = if matches!(
            function.kind,
            FunctionKind::Method(_)
                | FunctionKind::Static(_)
                | FunctionKind::Constructor(_)
                | FunctionKind::AsyncMethod(_)
                | FunctionKind::AsyncStatic(_)
                | FunctionKind::AsyncFreestanding
        ) {
            let resource = match &function.kind {
                FunctionKind::Method(resource)
                | FunctionKind::Static(resource)
                | FunctionKind::Constructor(resource)
                | FunctionKind::AsyncMethod(resource)
                | FunctionKind::AsyncStatic(resource) => *resource,
                _ => unreachable!(),
            };
            let resource_name = interface
                .types
                .iter()
                .find_map(|(name, id)| (*id == resource).then(|| name.clone()))
                .expect("resource name");
            format!(
                "{}_{}_method_{}",
                Self::rust_ident(&iface).to_lowercase(),
                Self::rust_ident(&resource_name).to_lowercase(),
                item
            )
        } else {
            format!("{}_{}", Self::rust_ident(&iface).to_lowercase(), item)
        };
        field.replace('-', "_")
    }

    fn export_core_name(&self, interface: &Interface, function: &Function) -> String {
        let iface_name = interface.name.clone().expect("interface name");
        let package_id = self.resolve.worlds[self.world]
            .package
            .expect("world package");
        let package = &self.resolve.packages[package_id].name;
        let version = package.version.as_ref().expect("package version");
        let version = format!("{}.{}.{}", version.major, version.minor, version.patch);
        let module = format!(
            "{}:{}/{}@{version}",
            package.namespace, package.name, iface_name
        );
        match &function.kind {
            FunctionKind::Freestanding => format!("{module}#{}", function.item_name()),
            FunctionKind::Method(resource)
            | FunctionKind::Static(resource)
            | FunctionKind::Constructor(resource)
            | FunctionKind::AsyncMethod(resource)
            | FunctionKind::AsyncStatic(resource) => {
                let resource_name = interface
                    .types
                    .iter()
                    .find_map(|(name, id)| (*id == *resource).then(|| name.clone()))
                    .expect("resource name");
                let op = match &function.kind {
                    FunctionKind::Method(_) | FunctionKind::AsyncMethod(_) => "#[method]",
                    FunctionKind::Static(_) | FunctionKind::AsyncStatic(_) => "#[static]",
                    FunctionKind::Constructor(_) => "#[constructor]",
                    _ => unreachable!(),
                };
                format!("{module}{op}{resource_name}.{}", function.item_name())
            }
            FunctionKind::AsyncFreestanding => format!("{module}#{}", function.item_name()),
        }
    }

    fn wasm_ty_name(ty: &WasmType) -> &'static str {
        match ty {
            WasmType::I32 => "i32",
            WasmType::I64 => "i64",
            WasmType::F32 => "f32",
            WasmType::F64 => "f64",
            WasmType::Pointer | WasmType::Length | WasmType::PointerOrI64 => "i32",
        }
    }
}

/// Generate bindings for an arbitrary resolved Core-Wasm WIT world.
pub fn generate_world(dir: &std::path::Path, world_name: &str) -> Result<String, String> {
    let (resolve, world) = parse_world(dir, world_name)?;
    Ok(Bindgen::new(resolve, world).generate())
}

/// Parse a WIT directory and return the world named `world_name`.
pub fn parse_world(dir: &std::path::Path, world_name: &str) -> Result<(Resolve, WorldId), String> {
    let mut resolve = Resolve::default();
    let (package, _) = resolve
        .push_dir(dir)
        .map_err(|error| format!("failed to parse WIT {}: {error}", dir.display()))?;
    let world = resolve.packages[package]
        .worlds
        .get(world_name)
        .copied()
        .ok_or_else(|| format!("world {world_name} not found"))?;
    Ok((resolve, world))
}

/// Collects the `Instruction` variants required by every imported function in
/// `world`, proving the canonical-ABI instruction stream covers the whole
/// world without panicking. Returns variant name -> occurrence count.
pub fn collect_world_import_instructions(
    resolve: &Resolve,
    world: WorldId,
) -> (BTreeMap<String, usize>, Vec<String>) {
    use wit_bindgen_core::abi::LiftLower;
    use wit_parser::abi::AbiVariant;

    struct Collector {
        counts: BTreeMap<String, usize>,
        sizes: SizeAlign,
    }
    impl Collector {
        fn new(resolve: &Resolve) -> Self {
            let mut sizes = SizeAlign::default();
            sizes.fill(resolve);
            Self {
                counts: BTreeMap::new(),
                sizes,
            }
        }
    }
    impl wit_bindgen_core::abi::Bindgen for Collector {
        type Operand = ();
        fn emit(
            &mut self,
            _resolve: &Resolve,
            inst: &wit_bindgen_core::abi::Instruction<'_>,
            _operands: &mut Vec<Self::Operand>,
            results: &mut Vec<Self::Operand>,
        ) {
            let debug = format!("{inst:?}");
            let name = debug
                .split([' ', '{'])
                .next()
                .unwrap_or("unknown")
                .to_owned();
            *self.counts.entry(name).or_insert(0) += 1;
            results.extend(std::iter::repeat_n((), inst.results_len()));
        }
        fn return_pointer(
            &mut self,
            _size: wit_parser::ArchitectureSize,
            _align: wit_parser::Alignment,
        ) -> Self::Operand {
        }
        fn push_block(&mut self) {}
        fn finish_block(&mut self, _operand: &mut Vec<Self::Operand>) {}
        fn sizes(&self) -> &SizeAlign {
            &self.sizes
        }
        fn is_list_canonical(&self, _resolve: &Resolve, _element: &wit_parser::Type) -> bool {
            false
        }
    }

    let mut collector = Collector::new(resolve);
    let mut functions = Vec::new();
    for (_, item) in resolve.worlds[world].imports.iter() {
        if let wit_parser::WorldItem::Interface { id, .. } = item {
            for function in resolve.interfaces[*id].functions.values() {
                functions.push(function.name.clone());
                wit_bindgen_core::abi::call(
                    resolve,
                    AbiVariant::GuestImport,
                    LiftLower::LowerArgsLiftResults,
                    function,
                    &mut collector,
                    false,
                );
            }
        }
    }
    (collector.counts, functions)
}
