// Generated by aegilex-core-bindgen from wit/world.wit. Do not edit.
pub mod core_host {

use anyhow::anyhow;
use wasmtime::{AsContext, AsContextMut, Caller, Instance, Linker, Memory, Store};
use wasmtime_wasi::{IoView, WasiView};

pub(crate) fn trap(message: impl std::fmt::Display) -> anyhow::Error {
    anyhow!("{message}")
}

fn mem_of<T>(caller: &mut Caller<'_, T>) -> anyhow::Result<Memory> {
    caller
        .get_export("memory")
        .and_then(|export| export.into_memory())
        .ok_or_else(|| trap("missing memory export"))
}

fn alloc<T>(caller: &mut Caller<'_, T>, mem: &Memory, size: usize, align: usize) -> anyhow::Result<i32> {
    let size = i32::try_from(size).map_err(|_| trap("allocation size out of range"))?;
    let align = i32::try_from(align).map_err(|_| trap("allocation alignment out of range"))?;
    let realloc = caller
        .get_export("cabi_realloc")
        .and_then(|export| export.into_func())
        .ok_or_else(|| trap("missing cabi_realloc"))?;
    let realloc = realloc
        .typed::<(i32, i32, i32, i32), i32>(&*caller)
        .map_err(|error| trap(format!("cabi_realloc typing failed: {error}")))?;
    realloc
        .call(&mut *caller, (0, 0, align, size))
        .map_err(|error| trap(format!("cabi_realloc failed: {error}")))
}

fn lift_string<T>(caller: &mut Caller<'_, T>, mem: &Memory, ptr: i32, len: i32) -> anyhow::Result<String> {
    let ptr = usize::try_from(ptr).map_err(|_| trap("string pointer out of range"))?;
    let len = usize::try_from(len).map_err(|_| trap("string length out of range"))?;
    let bytes = mem
        .data(caller.as_context())
        .get(ptr..)
        .and_then(|slice| slice.get(..len))
        .ok_or_else(|| trap("string out of bounds"))?;
    std::str::from_utf8(bytes)
        .map(str::to_owned)
        .map_err(|error| trap(format!("invalid UTF-8: {error}")))
}

fn lift_string_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize) -> anyhow::Result<String> {
    let ptr = read_i32_at(caller, mem, base, offset)?;
    let len = read_i32_at(caller, mem, base, offset + 4)?;
    lift_string(caller, mem, ptr, len)
}

fn lower_string_into<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize, value: &str) -> anyhow::Result<()> {
    let size = value.len();
    let ptr = alloc(caller, mem, size, 1)?;
    let ptr_usize = usize::try_from(ptr).map_err(|_| trap("allocation pointer out of range"))?;
    mem.data_mut(caller.as_context_mut())
        .get_mut(ptr_usize..)
        .and_then(|slice| slice.get_mut(..size))
        .ok_or_else(|| trap("allocation out of bounds"))?
        .copy_from_slice(value.as_bytes());
    let base = usize::try_from(base).map_err(|_| trap("result area out of range"))?;
    let slot = mem
        .data_mut(caller.as_context_mut())
        .get_mut(base + offset..)
        .and_then(|slice| slice.get_mut(..8))
        .ok_or_else(|| trap("result area out of bounds"))?;
    let size = i32::try_from(size).map_err(|_| trap("string too large"))?;
    slot[..4].copy_from_slice(&ptr.to_le_bytes());
    slot[4..].copy_from_slice(&size.to_le_bytes());
    Ok(())
}

fn read_bytes<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize, len: usize) -> anyhow::Result<Vec<u8>> {
    let base = usize::try_from(base).map_err(|_| trap("pointer out of range"))?;
    Ok(mem
        .data(caller.as_context())
        .get(base + offset..)
        .and_then(|slice| slice.get(..len))
        .ok_or_else(|| trap("read out of bounds"))?
        .to_vec())
}

fn read_i32_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize) -> anyhow::Result<i32> {
    let base = usize::try_from(base).map_err(|_| trap("pointer out of range"))?;
    let bytes = mem
        .data(caller.as_context())
        .get(base + offset..)
        .and_then(|slice| slice.get(..4))
        .ok_or_else(|| trap("read out of bounds"))?;
    Ok(i32::from_le_bytes(bytes.try_into().expect("4 bytes")))
}

fn read_i64_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize) -> anyhow::Result<i64> {
    let base = usize::try_from(base).map_err(|_| trap("pointer out of range"))?;
    let bytes = mem
        .data(caller.as_context())
        .get(base + offset..)
        .and_then(|slice| slice.get(..8))
        .ok_or_else(|| trap("read out of bounds"))?;
    Ok(i64::from_le_bytes(bytes.try_into().expect("8 bytes")))
}

fn read_f32_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize) -> anyhow::Result<f32> {
    Ok(f32::from_bits(read_i32_at(caller, mem, base, offset)? as u32))
}

fn read_f64_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize) -> anyhow::Result<f64> {
    Ok(f64::from_bits(read_i64_at(caller, mem, base, offset)? as u64))
}

fn write_u8_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize, value: i32) -> anyhow::Result<()> {
    let base = usize::try_from(base).map_err(|_| trap("pointer out of range"))?;
    let slot = mem.data_mut(caller.as_context_mut())
        .get_mut(base + offset)
        .ok_or_else(|| trap("write out of bounds"))?;
    *slot = value as u8;
    Ok(())
}

fn write_i32_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize, value: i32) -> anyhow::Result<()> {
    let base = usize::try_from(base).map_err(|_| trap("pointer out of range"))?;
    mem.data_mut(caller.as_context_mut())
        .get_mut(base + offset..)
        .and_then(|slice| slice.get_mut(..4))
        .ok_or_else(|| trap("write out of bounds"))?
        .copy_from_slice(&value.to_le_bytes());
    Ok(())
}

fn write_i64_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize, value: i64) -> anyhow::Result<()> {
    let base = usize::try_from(base).map_err(|_| trap("pointer out of range"))?;
    mem.data_mut(caller.as_context_mut())
        .get_mut(base + offset..)
        .and_then(|slice| slice.get_mut(..8))
        .ok_or_else(|| trap("write out of bounds"))?
        .copy_from_slice(&value.to_le_bytes());
    Ok(())
}

fn write_f32_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize, value: f32) -> anyhow::Result<()> {
    write_i32_at(&mut *caller, &mem, base, offset, value.to_bits() as i32)
}

fn write_f64_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize, value: f64) -> anyhow::Result<()> {
    write_i64_at(&mut *caller, &mem, base, offset, value.to_bits() as i64)
}

fn lower_list_string_into<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize, values: &[String]) -> anyhow::Result<()> {
    let elem_size = 8usize;
    let total = values.len().checked_mul(elem_size).ok_or_else(|| trap("list size overflow"))?;
    let elems = alloc(caller, mem, total, 4)?;
    let elems = usize::try_from(elems).map_err(|_| trap("list pointer out of range"))?;
    for (index, value) in values.iter().enumerate() {
        let element = elems.checked_add(index * elem_size).ok_or_else(|| trap("list offset overflow"))?;
        let ptr = alloc(caller, mem, value.len(), 1)?;
        let ptr = usize::try_from(ptr).map_err(|_| trap("string pointer out of range"))?;
        mem.data_mut(caller.as_context_mut())
            .get_mut(ptr..)
            .and_then(|slice| slice.get_mut(..value.len()))
            .ok_or_else(|| trap("string out of bounds"))?
            .copy_from_slice(value.as_bytes());
        let size = i32::try_from(value.len()).map_err(|_| trap("string too large"))?;
        let ptr = i32::try_from(ptr).map_err(|_| trap("string pointer out of range"))?;
        let slot = mem
            .data_mut(caller.as_context_mut())
            .get_mut(element..)
            .and_then(|slice| slice.get_mut(..8))
            .ok_or_else(|| trap("list element out of bounds"))?;
        slot[..4].copy_from_slice(&ptr.to_le_bytes());
        slot[4..].copy_from_slice(&size.to_le_bytes());
    }
    let elems = i32::try_from(elems).map_err(|_| trap("list pointer out of range"))?;
    let len = i32::try_from(values.len()).map_err(|_| trap("list length out of range"))?;
    write_i32_at(&mut *caller, &mem, base, offset, elems)?;
    write_i32_at(&mut *caller, &mem, base, offset + 4, len)?;
    Ok(())
}

fn lift_list_string_at<T>(caller: &mut Caller<'_, T>, mem: &Memory, base: i32, offset: usize) -> anyhow::Result<Vec<String>> {
    let ptr = read_i32_at(caller, mem, base, offset)?;
    let len = read_i32_at(caller, mem, base, offset + 4)?;
    let len = usize::try_from(len).map_err(|_| trap("list length out of range"))?;
    let mut values = Vec::with_capacity(len);
    for index in 0..len {
        let element_offset = index.checked_mul(8).ok_or_else(|| trap("list offset overflow"))?;
        values.push(lift_string_at(caller, mem, ptr, element_offset)?);
    }
    Ok(values)
}

    #[derive(Debug, Clone, PartialEq)]
    pub struct ProbeEchoInput {
    pub message: String,
    pub count: u32,
    }
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct CallbacksSink(pub u32);
    pub mod imports {
        use super::*;
        pub trait HostProbe {
            fn echo(caller: &mut Caller<'_, Self>, input: ProbeEchoInput) -> Result<String, String>
            where Self: Sized;
            fn maybe(caller: &mut Caller<'_, Self>, value: Option<u32>) -> Result<Result<u32, String>, String>
            where Self: Sized;
            fn log(caller: &mut Caller<'_, Self>, message: String) -> Result<(), String>
            where Self: Sized;
        }

        pub fn add_imports<T>(linker: &mut Linker<T>) -> anyhow::Result<()>
        where T: HostProbe + IoView + WasiView + 'static,
        {
            linker.func_wrap("aegilex:core-abi-probe/probe@0.1.0", "echo",
                |mut caller: Caller<'_, T>, arg0: i32, arg1: i32, arg2: i32, arg3: i32| -> anyhow::Result<()> {
                    let mem = mem_of(&mut caller)?;
let t0 = lift_string(&mut caller, &mem, arg0, arg1)?;
let t1 = ProbeEchoInput { message: t0, count: (arg2 as u32) };
let t2 = <T as HostProbe>::echo(&mut caller, t1).map_err(|error| trap(format!("{}::{} failed: {error}", "aegilex:core-abi-probe/probe@0.1.0", "echo")))?;
let t3 = t2;
let t4 = alloc(&mut caller, &mem, t3.len(), 1)?;
mem.data_mut(caller.as_context_mut()).get_mut(t4 as usize..).and_then(|slice| slice.get_mut(..t3.len())).ok_or_else(|| trap("allocation out of bounds"))?.copy_from_slice(t3.as_bytes());
let t5 = t3.len() as i32;
write_i32_at(&mut caller, &mem, arg3, 4, t5)?;
write_i32_at(&mut caller, &mem, arg3, 0, t4)?;
return Ok(());

                })?;
            linker.func_wrap("aegilex:core-abi-probe/probe@0.1.0", "maybe",
                |mut caller: Caller<'_, T>, arg0: i32, arg1: i32, arg2: i32| -> anyhow::Result<()> {
                    let mem = mem_of(&mut caller)?;
let v0 = if arg0 != 0 {
Some((arg1 as u32))
} else { None };
let t1 = <T as HostProbe>::maybe(&mut caller, v0).map_err(|error| trap(format!("{}::{} failed: {error}", "aegilex:core-abi-probe/probe@0.1.0", "maybe")))?;
match t1 {
Ok(e) => { {
write_u8_at(&mut caller, &mem, arg2, 0, 0)?;
write_i32_at(&mut caller, &mem, arg2, 4, (e as i32))?;
} }
Err(e) => { {
write_u8_at(&mut caller, &mem, arg2, 0, 1)?;
let t2 = e;
let t3 = alloc(&mut caller, &mem, t2.len(), 1)?;
mem.data_mut(caller.as_context_mut()).get_mut(t3 as usize..).and_then(|slice| slice.get_mut(..t2.len())).ok_or_else(|| trap("allocation out of bounds"))?.copy_from_slice(t2.as_bytes());
let t4 = t2.len() as i32;
write_i32_at(&mut caller, &mem, arg2, 8, t4)?;
write_i32_at(&mut caller, &mem, arg2, 4, t3)?;
} }
};
return Ok(());

                })?;
            linker.func_wrap("aegilex:core-abi-probe/probe@0.1.0", "log",
                |mut caller: Caller<'_, T>, arg0: i32, arg1: i32| -> anyhow::Result<()> {
                    let mem = mem_of(&mut caller)?;
let t0 = lift_string(&mut caller, &mem, arg0, arg1)?;
<T as HostProbe>::log(&mut caller, t0).map_err(|error| trap(format!("{}::{} failed: {error}", "aegilex:core-abi-probe/probe@0.1.0", "log")))?;
return Ok(());

                })?;
            Ok(())
        }

    }
    pub struct CoreExports {
        pub entry: wasmtime::TypedFunc<(), i32>,
        pub entry_post: wasmtime::TypedFunc<i32, ()>,
        callbacks_sink_method_push: wasmtime::TypedFunc<(i32, i32, i32), ()>,
        callbacks_sink_method_drain: wasmtime::TypedFunc<(i32), i32>,
        pub callbacks_sink_method_drain_post: wasmtime::TypedFunc<i32, ()>,
        callbacks_on_tick: wasmtime::TypedFunc<(), i32>,
        pub callbacks_on_tick_post: wasmtime::TypedFunc<i32, ()>,
    }

    impl CoreExports {
        pub fn new<T>(instance: &Instance, store: &mut Store<T>) -> Result<Self, String> {
        Ok(Self {
            entry: instance.get_typed_func::<(), i32>(&mut *store, "entry").map_err(|e| format!("missing entry export: {e}"))?,
            entry_post: instance.get_typed_func::<i32, ()>(&mut *store, "cabi_post_entry").map_err(|e| format!("missing cabi_post_entry: {e}"))?,
            callbacks_sink_method_push: instance.get_typed_func::<(i32, i32, i32), ()>(&mut *store, "aegilex:core-abi-probe/callbacks@0.1.0#[method]sink.push").map_err(|e| format!("missing aegilex:core-abi-probe/callbacks@0.1.0#[method]sink.push export: {e}"))?,
            callbacks_sink_method_drain: instance.get_typed_func::<(i32), i32>(&mut *store, "aegilex:core-abi-probe/callbacks@0.1.0#[method]sink.drain").map_err(|e| format!("missing aegilex:core-abi-probe/callbacks@0.1.0#[method]sink.drain export: {e}"))?,
            callbacks_sink_method_drain_post: instance.get_typed_func::<i32, ()>(&mut *store, "cabi_post_aegilex:core-abi-probe/callbacks@0.1.0#[method]sink.drain").map_err(|e| format!("missing cabi_post_aegilex:core-abi-probe/callbacks@0.1.0#[method]sink.drain: {e}"))?,
            callbacks_on_tick: instance.get_typed_func::<(), i32>(&mut *store, "aegilex:core-abi-probe/callbacks@0.1.0#on-tick").map_err(|e| format!("missing aegilex:core-abi-probe/callbacks@0.1.0#on-tick export: {e}"))?,
            callbacks_on_tick_post: instance.get_typed_func::<i32, ()>(&mut *store, "cabi_post_aegilex:core-abi-probe/callbacks@0.1.0#on-tick").map_err(|e| format!("missing cabi_post_aegilex:core-abi-probe/callbacks@0.1.0#on-tick: {e}"))?,
        })
        }
    }
}
