//! Core Wasm canonical-ABI vertical slice.
//!
//! These tests execute the `tests/core-abi-probe` Core Wasm guest (built for
//! `wasm32-wasip1`) using the bindings generated by `aegilex-core-bindgen`
//! from the probe WIT world. They prove value round-trips, the
//! `cabi_realloc`/`cabi_post_*` conventions, and synchronous host-import
//! reentry into a guest export.

include!(concat!(env!("OUT_DIR"), "/core_abi_probe_bindings.rs"));

use anyhow::{Result, anyhow};
use core_host::imports::HostProbe;
use wasmtime::{AsContext, Config, Engine, Instance, Linker, Module, Store};
use wasmtime_wasi::WasiCtxBuilder;
use wasmtime_wasi::preview1::{self, WasiP1Ctx};

fn probe_wasm_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(
        "../../../tests/core-abi-probe/target/wasm32-wasip1/release/aegilex_core_abi_probe.wasm",
    )
}

fn load_probe_module(engine: &Engine) -> Module {
    Module::from_file(engine, probe_wasm_path())
        .unwrap_or_else(|error| panic!("cannot load Core probe module: {error}"))
}

/// State shared by the probe store: Preview1 WASI plus a synchronous reentry
/// trace recorded by the generated host imports.
struct ProbeState {
    wasi: WasiP1Ctx,
    trace: Vec<String>,
    nested: bool,
}

impl HostProbe for ProbeState {
    fn echo(&mut self, input: core_host::ProbeEchoInput) -> Result<String, String> {
        let nested = self.nested;
        self.trace
            .push(format!("echo({}, nested={nested})", input.message));
        if !nested {
            self.nested = true;
            let nested_result = unsafe {
                crate::reentry::with_active_caller::<ProbeState, _>(|caller| {
                    let entry = caller
                        .get_export("entry")
                        .and_then(|export| export.into_func())
                        .ok_or_else(|| "missing entry export".to_owned())?
                        .typed::<(), i32>(&*caller)
                        .map_err(|error| format!("entry typing failed: {error}"))?;
                    let entry_retptr = entry
                        .call(&mut *caller, ())
                        .map_err(|error| format!("nested entry failed: {error}"))?;
                    let post = caller
                        .get_export("cabi_post_entry")
                        .and_then(|export| export.into_func())
                        .ok_or_else(|| "missing cabi_post_entry".to_owned())?
                        .typed::<i32, ()>(&*caller)
                        .map_err(|error| format!("cabi_post_entry typing failed: {error}"))?;
                    post.call(&mut *caller, entry_retptr)
                        .map_err(|error| format!("nested entry post failed: {error}"))
                })
            }
            .ok_or_else(|| "missing active host import caller".to_owned())?;
            self.nested = false;
            nested_result?;
        }
        Ok(format!("{}:{}", input.message, input.count))
    }

    fn maybe(&mut self, value: Option<u32>) -> Result<Result<u32, String>, String> {
        Ok(match value {
            Some(value) => Ok(value.checked_add(1).ok_or_else(|| "overflow".to_owned())?),
            None => Err("none".to_owned()),
        })
    }

    fn log(&mut self, message: String) -> Result<(), String> {
        self.trace.push(format!("log({message})"));
        Ok(())
    }

    fn list_echo(&mut self, values: Vec<u32>) -> Result<u32, String> {
        self.trace.push(format!("list-echo({values:?})"));
        values
            .into_iter()
            .try_fold(0u32, |sum, value| sum.checked_add(value).ok_or_else(|| "overflow".to_owned()))
    }
}

fn new_probe_store(engine: &Engine) -> Store<ProbeState> {
    let wasi = WasiCtxBuilder::new().build_p1();
    Store::new(
        engine,
        ProbeState {
            wasi,
            trace: Vec::new(),
            nested: false,
        },
    )
}

fn build_probe_linker(engine: &Engine) -> Result<Linker<ProbeState>> {
    let mut linker = Linker::new(engine);
    preview1::add_to_linker_sync(&mut linker, |state: &mut ProbeState| &mut state.wasi)
        .map_err(|error| anyhow!("cannot link WASI preview1: {error}"))?;
    core_host::imports::add_all_imports(&mut linker)
        .map_err(|error| anyhow!("cannot link generated imports: {error}"))?;
    Ok(linker)
}

/// Calls the generated `entry` export handle and runs its `cabi_post_entry`.
fn call_entry(store: &mut Store<ProbeState>, instance: &Instance) -> String {
    core_host::CoreExports::new(instance, &mut *store)
        .expect("core exports")
        .call_entry(instance, store)
        .expect("entry call")
}

#[test]
fn core_probe_module_is_a_core_module_and_dumps_abi() {
    let engine = Engine::new(&Config::new()).expect("engine");
    let module = load_probe_module(&engine);
    for import in module.imports() {
        println!(
            "IMPORT {} {} {:?}",
            import.module(),
            import.name(),
            import.ty()
        );
    }
    for export in module.exports() {
        println!("EXPORT {} {:?}", export.name(), export.ty());
    }
}

#[test]
fn generated_bindings_round_trip_values_through_core_abi() {
    let engine = Engine::new(&Config::new()).expect("engine");
    let module = load_probe_module(&engine);
    let linker = build_probe_linker(&engine).expect("linker");
    let mut store = new_probe_store(&engine);
    let instance = linker
        .instantiate(&mut store, &module)
        .expect("instantiate");

    // `entry` calls echo("hello", 7) and maybe(Some(7)) through generated host
    // imports, then returns "{echoed}/{maybe}" = "hello:7/8".
    let result = call_entry(&mut store, &instance);
    assert_eq!(result, "hello:7/8");
    assert_eq!(
        store.as_context().data().trace,
        vec![
            "echo(hello, nested=false)".to_owned(),
            "echo(hello, nested=true)".to_owned(),
            "log(entry: hello:7 maybe=8)".to_owned(),
            "log(entry: hello:7 maybe=8)".to_owned(),
        ]
    );
    assert!(!store.as_context().data().nested);
}

#[test]
fn generated_bindings_call_direct_scalars_and_lists() {
    let engine = Engine::new(&Config::new()).expect("engine");
    let module = load_probe_module(&engine);
    let linker = build_probe_linker(&engine).expect("linker");
    let mut store = new_probe_store(&engine);
    let instance = linker
        .instantiate(&mut store, &module)
        .expect("instantiate");
    let exports = core_host::CoreExports::new(&instance, &mut store).expect("core exports");

    assert_eq!(
        exports
            .call_direct_u32(&instance, &mut store, 41)
            .expect("direct u32"),
        42
    );
    assert_eq!(
        exports
            .call_direct_i64(&instance, &mut store, 41)
            .expect("direct i64"),
        -41
    );
    assert_eq!(
        exports
            .call_direct_f32(&mut store)
            .expect("direct f32")
            .to_bits(),
        0x4049_0fdb
    );
    assert_eq!(
        exports
            .call_direct_f64(&mut store)
            .expect("direct f64")
            .to_bits(),
        0x4009_21fb_5444_2d18
    );
    assert_eq!(
        exports
            .call_empty_list_values(&instance, &mut store)
            .expect("empty list"),
        Vec::<String>::new()
    );
    assert_eq!(
        exports
            .call_list_values(&instance, &mut store)
            .expect("list values"),
        vec!["alpha".to_owned(), "beta".to_owned()]
    );
    assert_eq!(
        exports
            .call_exercise_list_import(&mut store)
            .expect("list import"),
        14
    );

    assert_eq!(
        exports
            .call_callbacks_tick_count(&instance, &mut store)
            .expect("direct interface u32"),
        7
    );
    assert!(store
        .data()
        .trace
        .iter()
        .any(|entry| entry == "list-echo([2, 4, 8])"));
}

#[test]
fn generated_list_import_rejects_malformed_lengths_without_panicking() {
    let engine = Engine::new(&Config::new()).expect("engine");
    let wasm = wat::parse_str(
        r#"(module
            (import "aegilex:core-abi-probe/probe@0.1.0" "list-echo" (func $list-echo (param i32 i32) (result i32)))
            (memory (export "memory") 1)
            (func (export "entry") (result i32)
                i32.const 0
                i32.const -1
                call $list-echo)
        )"#,
    )
    .expect("malformed WAT");
    let module = Module::new(&engine, wasm).expect("malformed module");
    let linker = build_probe_linker(&engine).expect("linker");
    let mut store = new_probe_store(&engine);
    let instance = linker
        .instantiate(&mut store, &module)
        .expect("instantiate");
    let entry = instance
        .get_typed_func::<(), i32>(&mut store, "entry")
        .expect("entry");
    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        entry.call(&mut store, ())
    }));
    assert!(result.is_ok(), "malformed list import must not panic");
    assert!(result.unwrap().is_err(), "malformed list import must trap");
    assert!(!store.as_context().data().trace.iter().any(|entry| entry.starts_with("list-echo")));
}

#[test]
fn generated_host_import_reenters_guest_export_synchronously() {
    let engine = Engine::new(&Config::new()).expect("engine");
    let module = load_probe_module(&engine);
    let linker = build_probe_linker(&engine).expect("linker");
    let mut store = new_probe_store(&engine);
    let instance = linker
        .instantiate(&mut store, &module)
        .expect("instantiate");

    // The first `echo` host import sets `nested` and calls `entry` again while
    // its `Caller` is live. The nested `entry` runs its own echo/log imports
    // and returns before the outer trampoline lowers its result. The trace
    // proves: outer guest -> host import -> nested guest -> nested host import
    // -> nested return -> outer return.
    let result = call_entry(&mut store, &instance);
    assert_eq!(result, "hello:7/8");
    assert_eq!(
        store.as_context().data().trace,
        vec![
            "echo(hello, nested=false)".to_owned(),
            "echo(hello, nested=true)".to_owned(),
            "log(entry: hello:7 maybe=8)".to_owned(),
            "log(entry: hello:7 maybe=8)".to_owned(),
        ]
    );
    assert!(!store.as_context().data().nested);
}
