mod abi;
mod bindings;
mod config;
#[cfg(test)]
mod core_abi_tests;
#[cfg(test)]
mod core_canonical_tests;
#[cfg(test)]
mod core_loader_tests;
pub(crate) mod core_resources;
mod cxx_host;
mod reentry;

// Core Wasm canonical-ABI bindings and default-denied host trait
// implementations, generated by aegilex-core-bindgen from wit/world.wit.
include!(concat!(env!("OUT_DIR"), "/core_bindings.rs"));
mod core_store_impls {
    include!(concat!(env!("OUT_DIR"), "/store_denied_impls.rs"));
}
mod cxx_host_actor;
mod cxx_host_admin;
mod cxx_host_common;
mod cxx_host_inventory;
mod cxx_host_level;
mod cxx_host_player;
mod cxx_host_server;
mod cxx_host_ui;
mod cxx_runtime;
mod host;
mod manifest;
#[cfg(test)]
mod native_test_stub;
mod runtime;
