package aegilex:endstone@0.1.0;

// Endstone header: endstone/event/player/player_dimension_change_event.h
interface player-dimension-change-event {
    use player.{player};
    use types.{host-error};

    resource player-dimension-change-event { get-player: func() -> result<player, host-error>; get-from-dimension: func() -> result<string, host-error>; get-to-dimension: func() -> result<string, host-error>; }
}
