package aegilex:endstone@0.1.0;

// Endstone header: endstone/event/block/block_form_event.h
interface block-form-event {
    use block.{block};
    use types.{host-error};

    resource block-form-event { get-block: func() -> result<block, host-error>; is-cancelled: func() -> result<bool, host-error>; set-cancelled: func(cancelled: bool) -> result<_, host-error>; }
}
