package aegilex:endstone@0.1.0;

// Endstone header: endstone/event/server/server_list_ping_event.h
interface server-list-ping-event {
    use types.{host-error};

    resource server-list-ping-event { get-motd: func() -> result<string, host-error>; set-motd: func(motd: string) -> result<_, host-error>; get-server-guid: func() -> result<string, host-error>; set-server-guid: func(server-guid: string) -> result<_, host-error>; get-local-port: func() -> result<s32, host-error>; set-local-port: func(local-port: s32) -> result<_, host-error>; get-local-port-v6: func() -> result<s32, host-error>; set-local-port-v6: func(local-port-v6: s32) -> result<_, host-error>; is-cancelled: func() -> result<bool, host-error>; set-cancelled: func(cancelled: bool) -> result<_, host-error>; }
}
