package aegilex:endstone@0.1.0;

// Endstone header: endstone/event/chunk/chunk_unload_event.h
interface chunk-unload-event {
    use types.{host-error};

    resource chunk-unload-event { get-chunk-x: func() -> result<s32, host-error>; get-chunk-z: func() -> result<s32, host-error>; get-dimension: func() -> result<string, host-error>; }
}
