package aegilex:endstone@0.1.0;

// Endstone header: endstone/event/player/player_command_event.h
interface player-command-event {
    use player.{player};
    use types.{host-error};

    resource player-command-event { get-player: func() -> result<player, host-error>; get-command: func() -> result<string, host-error>; set-command: func(command: string) -> result<_, host-error>; is-cancelled: func() -> result<bool, host-error>; set-cancelled: func(cancelled: bool) -> result<_, host-error>; }
}
