package aegilex:endstone@0.1.0;

// Endstone header: endstone/event/block/block_piston_extend_event.h
interface block-piston-extend-event {
    use block.{block};
    use block-face.{block-face};
    use types.{host-error};

    resource block-piston-extend-event { get-block: func() -> result<block, host-error>; get-direction: func() -> result<block-face, host-error>; is-cancelled: func() -> result<bool, host-error>; set-cancelled: func(cancelled: bool) -> result<_, host-error>; }
}
