package aegilex:endstone@0.1.0;

// Endstone header: endstone/form/controls/header.h
// Copied form control value imported by world plugin.
interface form-header {
    use message.{message};

    record header {
        label: message,
    }
}
