package aegilex:endstone@0.1.0;

// Endstone header: endstone/form/controls/step_slider.h
// Copied form control value imported by world plugin.
interface form-step-slider {
    use form-dropdown.{dropdown};

    type step-slider = dropdown;
}
