package aegilex:endstone@0.1.0;

// Endstone header: endstone/form/controls/toggle.h
// Copied form control value imported by world plugin.
interface form-toggle {
    use message.{message};

    record toggle {
        label: message,
        default-value: bool,
    }
}
