package aegilex:endstone@0.1.0;

// Endstone header: endstone/message.h
interface message {
    use translatable.{translatable};

    variant message {
        plain-text(string),
        translatable(translatable),
    }
}
