package aegilex:endstone@0.1.0;

// Endstone header: endstone/scoreboard/score.h
interface score {
    record score {
        objective-name: string,
        value: s32,
        score-set: bool,
    }
}
