package aegilex:endstone@0.1.0;

// Endstone header: endstone/util/image.h
interface image {
    record image {
        width: u32,
        height: u32,
        depth: u32,
        data: list<u8>,
    }
}
