package aegilex:endstone@0.1.0;

world plugin {
    import actor;
    import block;
    import block-data;
    import block-face;
    import block-state;
    import block-type;
    import block-command-sender;
    import boss-bar;
    import bar-color;
    import bar-flag;
    import bar-style;
    import ban-list;
    import commands;
    import command-sender;
    import damage-source;
    import events;
    import packet;
    import packet-send-event;
    import packet-receive-event;
    import socket-address;
    import player-join-event;
    import player-quit-event;
    import player-chat-event;
    import player-kick-event;
    import player-command-event;
    import player-game-mode-change-event;
    import player-teleport-event;
    import player-drop-item-event;
    import block-break-event;
    import block-place-event;
    import actor-damage-event;
    import server-command-event;
    import player-bed-enter-event;
    import player-bed-leave-event;
    import player-dimension-change-event;
    import player-emote-event;
    import player-interact-event;
    import player-interact-actor-event;
    import player-item-consume-event;
    import player-item-held-event;
    import player-jump-event;
    import player-login-event;
    import player-move-event;
    import player-pickup-item-event;
    import player-portal-event;
    import player-respawn-event;
    import player-skin-change-event;
    import block-cook-event;
    import block-explode-event;
    import block-form-event;
    import block-from-to-event;
    import block-grow-event;
    import block-piston-extend-event;
    import block-piston-retract-event;
    import leaves-decay-event;
    import chunk-load-event;
    import chunk-unload-event;
    import weather-change-event;
    import thunder-change-event;
    import actor-death-event;
    import actor-explode-event;
    import actor-knockback-event;
    import actor-remove-event;
    import actor-spawn-event;
    import actor-teleport-event;
    import player-death-event;
    import broadcast-message-event;
    import server-list-ping-event;
    import plugin-enable-event;
    import plugin-disable-event;
    import server-load-event;
    import chunk;
    import dimension;
    import location;
    import vector;
    import color;
    import uuid;
    import identifier;
    import logger;
    import inventory;
    import item-actor;
    import item-factory;
    import item-meta;
    import writable-book-meta;
    import book-meta;
    import crossbow-meta;
    import map-meta;
    import nbt;
    import item-stack;
    import item-type;
    import equipment-slot;
    import image;
    import level;
    import message;
    import translatable;
    import language;
    import player;
    import skin;
    import player-inventory;
    import permissible;
    import permission-attachment;
    import permission-definition;
    import permission-default;
    import permission-level;
    import scoreboard;
    import objective;
    import score-entry;
    import score;
    import criteria;
    import display-slot;
    import objective-sort-order;
    import render-type;
    import map-view;
    import plugin-context;
    import plugin-types;
    import plugin-command;
    import task;
    import tasks;
    import player-form;
    import form;
    import action-form;
    import message-form;
    import modal-form;
    import form-button;
    import form-divider;
    import form-header;
    import form-label;
    import form-dropdown;
    import form-slider;
    import form-step-slider;
    import form-text-input;
    import form-toggle;
    import plugin-manager;
    import service-bus;
    import service-priority;
    import map-renderer;
    import map-canvas;
    import map-cursor;
    import map-initialize-event;
    import script-message-event;

    use plugin-metadata.{metadata};

    export metadata: func() -> metadata;
    export on-load: func() -> result<_, string>;
    export on-enable: func() -> result<_, string>;
    export on-disable: func();
    export commands;
    export events;
    export tasks;
    export form-callbacks;
    export service-callbacks;
    export map-renderer-callbacks;
}
